// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"

	"github.com/tarantool/go-option"
)

func TestAny_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someAny := option.SomeAny("hello")
		assert.True(t, someAny.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyAny := option.NoneAny()
		assert.False(t, emptyAny.IsSome())
	})
}

func TestAny_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someAny := option.SomeAny("hello")
		assert.False(t, someAny.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyAny := option.NoneAny()
		assert.True(t, emptyAny.IsZero())
	})
}

func TestAny_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someAny := option.SomeAny("hello")
		assert.False(t, someAny.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyAny := option.NoneAny()
		assert.True(t, emptyAny.IsNil())
	})
}

func TestAny_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someAny := option.SomeAny("hello")
		val, ok := someAny.Get()
		require.True(t, ok)
		assert.EqualValues(t, "hello", val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyAny := option.NoneAny()
		_, ok := emptyAny.Get()
		require.False(t, ok)
	})
}

func TestAny_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someAny := option.SomeAny("hello")
		assert.EqualValues(t, "hello", someAny.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyAny := option.NoneAny()
		assert.Panics(t, func() {
			emptyAny.MustGet()
		})
	})
}

func TestAny_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someAny := option.SomeAny("hello")
		assert.EqualValues(t, "hello", someAny.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyAny := option.NoneAny()
		assert.NotPanics(t, func() {
			emptyAny.Unwrap()
		})
	})
}

func TestAny_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someAny := option.SomeAny("hello")
		assert.EqualValues(t, "hello", someAny.UnwrapOr("bye"))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyAny := option.NoneAny()
		assert.EqualValues(t, "bye", emptyAny.UnwrapOr("bye"))
	})
}

func TestAny_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someAny := option.SomeAny("hello")
		assert.EqualValues(t, "hello", someAny.UnwrapOrElse(func() any {
			return "bye"
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyAny := option.NoneAny()
		assert.EqualValues(t, "bye", emptyAny.UnwrapOrElse(func() any {
			return "bye"
		}))
	})
}

func TestAny_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someAny := option.SomeAny("hello")
		err := someAny.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Any
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, "hello", unmarshaled.Unwrap())
	})

	t.Run("some_1", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someAny := option.SomeAny(123)
		err := someAny.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Any
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, 123, unmarshaled.Unwrap())
	})

	t.Run("some_2", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someAny := option.SomeAny(true)
		err := someAny.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Any
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, true, unmarshaled.Unwrap())
	})

	t.Run("some_3", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someAny := option.SomeAny(123.456)
		err := someAny.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Any
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, 123.456, unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyAny := option.NoneAny()
		err := emptyAny.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Any
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}

func ExampleSomeAny() {
	opt := option.SomeAny("hello")
	if opt.IsSome() {
		fmt.Println(opt.Unwrap())
	}
	// Output: hello
}

func ExampleNoneAny() {
	opt := option.NoneAny()
	if opt.IsZero() {
		fmt.Println("value is absent")
	}
	// Output: value is absent
}

func ExampleAny_IsSome() {
	some := option.SomeAny("hello")
	none := option.NoneAny()
	fmt.Println(some.IsSome())
	fmt.Println(none.IsSome())
	// Output:
	// true
	// false
}

func ExampleAny_IsZero() {
	some := option.SomeAny("hello")
	none := option.NoneAny()
	fmt.Println(some.IsZero())
	fmt.Println(none.IsZero())
	// Output:
	// false
	// true
}

func ExampleAny_IsNil() {
	some := option.SomeAny("hello")
	none := option.NoneAny()
	fmt.Println(some.IsNil() == some.IsZero())
	fmt.Println(none.IsNil() == none.IsZero())
	// Output:
	// true
	// true
}

func ExampleAny_Get() {
	some := option.SomeAny("hello")
	none := option.NoneAny()
	val, ok := some.Get()
	fmt.Println(val, ok)
	val, ok = none.Get()
	fmt.Println(val, ok)
	// Output:
	// hello true
	// <nil> false
}

func ExampleAny_MustGet() {
	some := option.SomeAny("hello")
	fmt.Println(some.MustGet())
	// Output: hello
}

func ExampleAny_MustGet_panic() {
	none := option.NoneAny()
	eof := false
	defer func() {
		if !eof {
			fmt.Println("panic!", recover())
		}
	}()
	fmt.Println(none.MustGet())
	eof = true
	// Output: panic! optional value is not set
}

func ExampleAny_Unwrap() {
	some := option.SomeAny("hello")
	none := option.NoneAny()
	fmt.Println(some.Unwrap())
	fmt.Println(none.Unwrap())
	// Output:
	// hello
	// <nil>
}

func ExampleAny_UnwrapOr() {
	some := option.SomeAny("hello")
	none := option.NoneAny()
	fmt.Println(some.UnwrapOr("bye"))
	fmt.Println(none.UnwrapOr("bye"))
	// Output:
	// hello
	// bye
}

func ExampleAny_UnwrapOrElse() {
	some := option.SomeAny("hello")
	none := option.NoneAny()
	fmt.Println(some.UnwrapOrElse(func() any {
		return "bye"
	}))
	fmt.Println(none.UnwrapOrElse(func() any {
		return "bye"
	}))
	// Output:
	// hello
	// bye
}
