// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option

import (
	"bytes"
	"encoding/json"

	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"
)

// Any represents an optional value of type any.
// It can either hold a valid any (IsSome == true) or be empty (IsZero == true).
type Any struct {
	value  any
	exists bool
}

var _ commonInterface[any] = (*Any)(nil)

// SomeAny creates an optional Any with the given any value.
// The returned Any will have IsSome() == true and IsZero() == false.
func SomeAny(value any) Any {
	return Any{
		value:  value,
		exists: true,
	}
}

// NoneAny creates an empty optional Any value.
// The returned Any will have IsSome() == false and IsZero() == true.
func NoneAny() Any {
	return Any{
		exists: false,
		value:  zero[any](),
	}
}

// IsSome returns true if the Any contains a value.
// This indicates the value is explicitly set (not None).
func (o Any) IsSome() bool {
	return o.exists
}

// IsZero returns true if the Any does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o Any) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o Any) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of any, false).
//
// Recommended usage:
//
//	if value, ok := o.Get(); ok {
//	    // use value
//	}
func (o Any) Get() (any, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o Any) MustGet() any {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for any.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o Any) Unwrap() any {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
func (o Any) UnwrapOr(defaultValue any) any {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
func (o Any) UnwrapOrElse(defaultValue func() any) any {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

// EncodeMsgpack encodes the Any value using MessagePack format.
// - If the value is present, it is encoded as any.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o Any) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return newEncodeError("Any", encodeAny(encoder, o.value))
	}

	return newEncodeError("Any", encoder.EncodeNil())
}

// DecodeMsgpack decodes a Any value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneAny)
//   - any: interpreted as a present value (SomeAny)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on any: exists = true, value = decoded value
func (o *Any) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return newDecodeError("Any", err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return newDecodeError("Any", decoder.Skip())
	case checkAny(code):
		o.value, err = decodeAny(decoder)
		if err != nil {
			return newDecodeError("Any", err)
		}
		o.exists = true

		return err
	default:
		return newDecodeWithCodeError("Any", code)
	}
}

// MarshalJSON implements the json.Marshaler interface.
//   - If the value is present, it is encoded exactly as json.Marshal encodes
//     the any value itself.
//   - If the value is absent (None), it is encoded as JSON null.
//
// A present nil any is encoded as JSON null too, so it decodes back
// as an absent value.
//
// A struct field of type Any with the "omitzero" JSON tag option is
// omitted when the value is absent, since IsZero reports absence.
// The "omitempty" option has no effect on it.
func (o Any) MarshalJSON() ([]byte, error) {
	if !o.exists {
		return []byte("null"), nil
	}

	return json.Marshal(&o.value)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
//   - JSON null is decoded as no value (NoneAny).
//   - Any other JSON value is decoded as any and stored as a present value.
//
// An error of decoding any is returned unchanged, and the receiver
// is left intact.
func (o *Any) UnmarshalJSON(data []byte) error {
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		*o = NoneAny()

		return nil
	}

	var value any

	err := json.Unmarshal(data, &value)
	if err != nil {
		return err
	}

	*o = SomeAny(value)

	return nil
}

// MarshalYAML implements the Marshaler interface of gopkg.in/yaml.v3
// (and yaml.v2) without depending on it.
//   - If the value is present, it returns a pointer to it, so the value is
//     encoded exactly as the YAML encoder encodes any itself.
//   - If the value is absent (None), it returns nil, which is encoded as null.
//
// A struct field of type Any with the "omitempty" YAML tag option is
// omitted when the value is absent, since the encoder consults IsZero.
func (o Any) MarshalYAML() (any, error) {
	if !o.exists {
		return nil, nil
	}

	return &o.value, nil
}

// UnmarshalYAML implements the obsolete Unmarshaler interface of
// gopkg.in/yaml.v3 (the only one of yaml.v2) without depending on it.
//   - A null value is decoded as no value (NoneAny).
//   - Any other value is decoded as any and stored as a present value.
//
// gopkg.in/yaml.v3 never calls this method for a null node (null, ~ or an
// empty value): it leaves the receiver unchanged. Decoding null into a zero
// Any therefore yields None, but decoding it into a present value
// keeps that value.
//
// An error of decoding any is returned unchanged, and the receiver
// is left intact.
func (o *Any) UnmarshalYAML(unmarshal func(any) error) error {
	var value *any

	err := unmarshal(&value)
	if err != nil {
		return err
	}

	if value == nil {
		*o = NoneAny()

		return nil
	}

	*o = SomeAny(*value)

	return nil
}
