// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option

import (
	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"
)

// Bool represents an optional value of type bool.
// It can either hold a valid bool (IsSome == true) or be empty (IsZero == true).
type Bool struct {
	value  bool
	exists bool
}

// SomeBool creates an optional Bool with the given bool value.
// The returned Bool will have IsSome() == true and IsZero() == false.
//
// Example:
//
//	o := SomeBool(true)
//	if o.IsSome() {
//	    v := o.Unwrap() // v == true
//	}
func SomeBool(value bool) Bool {
	return Bool{
		value:  value,
		exists: true,
	}
}

// NoneBool creates an empty optional Bool value.
// The returned Bool will have IsSome() == false and IsZero() == true.
//
// Example:
//
//	o := NoneBool()
//	if o.IsZero() {
//	    fmt.Println("value is absent")
//	}
func NoneBool() Bool {
	return Bool{
		exists: false,
		value:  zero[bool](),
	}
}

// IsSome returns true if the Bool contains a value.
// This indicates the value is explicitly set (not None).
func (o Bool) IsSome() bool {
	return o.exists
}

// IsZero returns true if the Bool does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o Bool) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o Bool) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of bool, false).
//
// Recommended usage:
//
//	if value, ok := o.Get(); ok {
//	    // use value
//	}
func (o Bool) Get() (bool, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o Bool) MustGet() bool {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for bool.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o Bool) Unwrap() bool {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
//
// Example:
//
//	o := NoneBool()
//	v := o.UnwrapOr(someDefaultBool)
func (o Bool) UnwrapOr(defaultValue bool) bool {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
//
// Example:
//
//	o := NoneBool()
//	v := o.UnwrapOrElse(func() bool { return computeDefault() })
func (o Bool) UnwrapOrElse(defaultValue func() bool) bool {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

// EncodeMsgpack encodes the Bool value using MessagePack format.
// - If the value is present, it is encoded as bool.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o Bool) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return newEncodeError("Bool", encodeBool(encoder, o.value))
	}

	return newEncodeError("Bool", encoder.EncodeNil())
}

// DecodeMsgpack decodes a Bool value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneBool)
//   - bool: interpreted as a present value (SomeBool)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on bool: exists = true, value = decoded value
func (o *Bool) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return newDecodeError("Bool", err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return newDecodeError("Bool", decoder.Skip())
	case checkBool(code):
		o.value, err = decodeBool(decoder)
		if err != nil {
			return newDecodeError("Bool", err)
		}
		o.exists = true

		return err
	default:
		return newDecodeWithCodeError("Bool", code)
	}
}
