// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option

import (
	"bytes"
	"encoding/json"

	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"
)

// Bool represents an optional value of type bool.
// It can either hold a valid bool (IsSome == true) or be empty (IsZero == true).
type Bool struct {
	value  bool
	exists bool
}

var _ commonInterface[bool] = (*Bool)(nil)

// SomeBool creates an optional Bool with the given bool value.
// The returned Bool will have IsSome() == true and IsZero() == false.
func SomeBool(value bool) Bool {
	return Bool{
		value:  value,
		exists: true,
	}
}

// NoneBool creates an empty optional Bool value.
// The returned Bool will have IsSome() == false and IsZero() == true.
func NoneBool() Bool {
	return Bool{
		exists: false,
		value:  zero[bool](),
	}
}

// IsSome returns true if the Bool contains a value.
// This indicates the value is explicitly set (not None).
func (o Bool) IsSome() bool {
	return o.exists
}

// IsZero returns true if the Bool does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o Bool) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o Bool) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of bool, false).
//
// Recommended usage:
//
//	if value, ok := o.Get(); ok {
//	    // use value
//	}
func (o Bool) Get() (bool, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o Bool) MustGet() bool {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for bool.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o Bool) Unwrap() bool {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
func (o Bool) UnwrapOr(defaultValue bool) bool {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
func (o Bool) UnwrapOrElse(defaultValue func() bool) bool {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

// EncodeMsgpack encodes the Bool value using MessagePack format.
// - If the value is present, it is encoded as bool.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o Bool) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return newEncodeError("Bool", encodeBool(encoder, o.value))
	}

	return newEncodeError("Bool", encoder.EncodeNil())
}

// DecodeMsgpack decodes a Bool value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneBool)
//   - bool: interpreted as a present value (SomeBool)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on bool: exists = true, value = decoded value
func (o *Bool) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return newDecodeError("Bool", err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return newDecodeError("Bool", decoder.Skip())
	case checkBool(code):
		o.value, err = decodeBool(decoder)
		if err != nil {
			return newDecodeError("Bool", err)
		}
		o.exists = true

		return err
	default:
		return newDecodeWithCodeError("Bool", code)
	}
}

// MarshalJSON implements the json.Marshaler interface.
//   - If the value is present, it is encoded exactly as json.Marshal encodes
//     the bool value itself.
//   - If the value is absent (None), it is encoded as JSON null.
//
// A struct field of type Bool with the "omitzero" JSON tag option is
// omitted when the value is absent, since IsZero reports absence.
// The "omitempty" option has no effect on it.
func (o Bool) MarshalJSON() ([]byte, error) {
	if !o.exists {
		return []byte("null"), nil
	}

	return json.Marshal(&o.value)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
//   - JSON null is decoded as no value (NoneBool).
//   - Any other JSON value is decoded as bool and stored as a present value.
//
// An error of decoding bool is returned unchanged, and the receiver
// is left intact.
func (o *Bool) UnmarshalJSON(data []byte) error {
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		*o = NoneBool()

		return nil
	}

	var value bool

	err := json.Unmarshal(data, &value)
	if err != nil {
		return err
	}

	*o = SomeBool(value)

	return nil
}

// MarshalYAML implements the Marshaler interface of gopkg.in/yaml.v3
// (and yaml.v2) without depending on it.
//   - If the value is present, it returns a pointer to it, so the value is
//     encoded exactly as the YAML encoder encodes bool itself.
//   - If the value is absent (None), it returns nil, which is encoded as null.
//
// A struct field of type Bool with the "omitempty" YAML tag option is
// omitted when the value is absent, since the encoder consults IsZero.
func (o Bool) MarshalYAML() (any, error) {
	if !o.exists {
		return nil, nil
	}

	return &o.value, nil
}

// UnmarshalYAML implements the obsolete Unmarshaler interface of
// gopkg.in/yaml.v3 (the only one of yaml.v2) without depending on it.
//   - A null value is decoded as no value (NoneBool).
//   - Any other value is decoded as bool and stored as a present value.
//
// gopkg.in/yaml.v3 never calls this method for a null node (null, ~ or an
// empty value): it leaves the receiver unchanged. Decoding null into a zero
// Bool therefore yields None, but decoding it into a present value
// keeps that value.
//
// An error of decoding bool is returned unchanged, and the receiver
// is left intact.
func (o *Bool) UnmarshalYAML(unmarshal func(any) error) error {
	var value *bool

	err := unmarshal(&value)
	if err != nil {
		return err
	}

	if value == nil {
		*o = NoneBool()

		return nil
	}

	*o = SomeBool(*value)

	return nil
}
