// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"

	"github.com/tarantool/go-option"
)

func TestBool_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someBool := option.SomeBool(true)
		assert.True(t, someBool.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyBool := option.NoneBool()
		assert.False(t, emptyBool.IsSome())
	})
}

func TestBool_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someBool := option.SomeBool(true)
		assert.False(t, someBool.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyBool := option.NoneBool()
		assert.True(t, emptyBool.IsZero())
	})
}

func TestBool_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someBool := option.SomeBool(true)
		assert.False(t, someBool.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyBool := option.NoneBool()
		assert.True(t, emptyBool.IsNil())
	})
}

func TestBool_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someBool := option.SomeBool(true)
		val, ok := someBool.Get()
		require.True(t, ok)
		assert.EqualValues(t, true, val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyBool := option.NoneBool()
		_, ok := emptyBool.Get()
		require.False(t, ok)
	})
}

func TestBool_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someBool := option.SomeBool(true)
		assert.EqualValues(t, true, someBool.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyBool := option.NoneBool()
		assert.Panics(t, func() {
			emptyBool.MustGet()
		})
	})
}

func TestBool_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someBool := option.SomeBool(true)
		assert.EqualValues(t, true, someBool.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyBool := option.NoneBool()
		assert.NotPanics(t, func() {
			emptyBool.Unwrap()
		})
	})
}

func TestBool_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someBool := option.SomeBool(true)
		assert.EqualValues(t, true, someBool.UnwrapOr(false))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyBool := option.NoneBool()
		assert.EqualValues(t, false, emptyBool.UnwrapOr(false))
	})
}

func TestBool_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someBool := option.SomeBool(true)
		assert.EqualValues(t, true, someBool.UnwrapOrElse(func() bool {
			return false
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyBool := option.NoneBool()
		assert.EqualValues(t, false, emptyBool.UnwrapOrElse(func() bool {
			return false
		}))
	})
}

func TestBool_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someBool := option.SomeBool(true)
		err := someBool.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Bool
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, true, unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyBool := option.NoneBool()
		err := emptyBool.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Bool
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}

func ExampleSomeBool() {
	opt := option.SomeBool(true)
	if opt.IsSome() {
		fmt.Println(opt.Unwrap())
	}
	// Output: true
}

func ExampleNoneBool() {
	opt := option.NoneBool()
	if opt.IsZero() {
		fmt.Println("value is absent")
	}
	// Output: value is absent
}

func ExampleBool_IsSome() {
	some := option.SomeBool(true)
	none := option.NoneBool()
	fmt.Println(some.IsSome())
	fmt.Println(none.IsSome())
	// Output:
	// true
	// false
}

func ExampleBool_IsZero() {
	some := option.SomeBool(true)
	none := option.NoneBool()
	fmt.Println(some.IsZero())
	fmt.Println(none.IsZero())
	// Output:
	// false
	// true
}

func ExampleBool_IsNil() {
	some := option.SomeBool(true)
	none := option.NoneBool()
	fmt.Println(some.IsNil() == some.IsZero())
	fmt.Println(none.IsNil() == none.IsZero())
	// Output:
	// true
	// true
}

func ExampleBool_Get() {
	some := option.SomeBool(true)
	none := option.NoneBool()
	val, ok := some.Get()
	fmt.Println(val, ok)
	val, ok = none.Get()
	fmt.Println(val, ok)
	// Output:
	// true true
	// false false
}

func ExampleBool_MustGet() {
	some := option.SomeBool(true)
	fmt.Println(some.MustGet())
	// Output: true
}

func ExampleBool_MustGet_panic() {
	none := option.NoneBool()
	eof := false
	defer func() {
		if !eof {
			fmt.Println("panic!", recover())
		}
	}()
	fmt.Println(none.MustGet())
	eof = true
	// Output: panic! optional value is not set
}

func ExampleBool_Unwrap() {
	some := option.SomeBool(true)
	none := option.NoneBool()
	fmt.Println(some.Unwrap())
	fmt.Println(none.Unwrap())
	// Output:
	// true
	// false
}

func ExampleBool_UnwrapOr() {
	some := option.SomeBool(true)
	none := option.NoneBool()
	fmt.Println(some.UnwrapOr(false))
	fmt.Println(none.UnwrapOr(false))
	// Output:
	// true
	// false
}

func ExampleBool_UnwrapOrElse() {
	some := option.SomeBool(true)
	none := option.NoneBool()
	fmt.Println(some.UnwrapOrElse(func() bool {
		return false
	}))
	fmt.Println(none.UnwrapOrElse(func() bool {
		return false
	}))
	// Output:
	// true
	// false
}
