// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"
	"gopkg.in/yaml.v3"

	"github.com/tarantool/go-option"
)

func TestByte_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.True(t, someByte.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.False(t, emptyByte.IsSome())
	})
}

func TestByte_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.False(t, someByte.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.True(t, emptyByte.IsZero())
	})
}

func TestByte_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.False(t, someByte.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.True(t, emptyByte.IsNil())
	})
}

func TestByte_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		val, ok := someByte.Get()
		require.True(t, ok)
		assert.EqualValues(t, 12, val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		_, ok := emptyByte.Get()
		require.False(t, ok)
	})
}

func TestByte_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.EqualValues(t, 12, someByte.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.Panics(t, func() {
			emptyByte.MustGet()
		})
	})
}

func TestByte_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.EqualValues(t, 12, someByte.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.NotPanics(t, func() {
			emptyByte.Unwrap()
		})
	})
}

func TestByte_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.EqualValues(t, 12, someByte.UnwrapOr(13))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.EqualValues(t, 13, emptyByte.UnwrapOr(13))
	})
}

func TestByte_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.EqualValues(t, 12, someByte.UnwrapOrElse(func() byte {
			return 13
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.EqualValues(t, 13, emptyByte.UnwrapOrElse(func() byte {
			return 13
		}))
	})
}

func TestByte_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someByte := option.SomeByte(12)
		err := someByte.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Byte
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, 12, unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyByte := option.NoneByte()
		err := emptyByte.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Byte
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}

func TestByte_MarshalJSON(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.SomeByte(12))
		require.NoError(t, err)
		assert.Equal(t, `12`, string(data))
	})

	t.Run("some_as_inner_0", func(t *testing.T) {
		t.Parallel()

		expected, err := json.Marshal(byte(12))
		require.NoError(t, err)

		data, err := json.Marshal(option.SomeByte(12))
		require.NoError(t, err)
		assert.Equal(t, string(expected), string(data))
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.SomeByte(0))
		require.NoError(t, err)
		assert.Equal(t, `0`, string(data))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.NoneByte())
		require.NoError(t, err)
		assert.Equal(t, "null", string(data))
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some option.Byte `json:"some"`
			None option.Byte `json:"none"`
		}

		data, err := json.Marshal(wrapper{
			Some: option.SomeByte(12),
			None: option.NoneByte(),
		})
		require.NoError(t, err)
		assert.Equal(t, `{"some":12,"none":null}`, string(data))
	})

	t.Run("omitzero", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Value option.Byte `json:"value,omitzero"`
		}

		data, err := json.Marshal(wrapper{Value: option.NoneByte()})
		require.NoError(t, err)
		assert.Equal(t, "{}", string(data))

		data, err = json.Marshal(wrapper{Value: option.SomeByte(0)})
		require.NoError(t, err)
		assert.Equal(t, `{"value":0}`, string(data))
	})
}

func TestByte_UnmarshalJSON(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var opt option.Byte
		require.NoError(t, json.Unmarshal([]byte(`12`), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("roundtrip_0", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.SomeByte(12))
		require.NoError(t, err)

		var opt option.Byte
		require.NoError(t, json.Unmarshal(data, &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		var opt option.Byte
		require.NoError(t, json.Unmarshal([]byte(`0`), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 0, opt.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeByte(12)
		require.NoError(t, json.Unmarshal([]byte("null"), &opt))
		assert.False(t, opt.IsSome())
		assert.Zero(t, opt.Unwrap())
	})

	t.Run("none_with_spaces", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeByte(12)
		require.NoError(t, opt.UnmarshalJSON([]byte(" null\n")))
		assert.False(t, opt.IsSome())
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some   option.Byte `json:"some"`
			None   option.Byte `json:"none"`
			Absent option.Byte `json:"absent"`
		}

		var out wrapper
		err := json.Unmarshal([]byte(`{"some":12,"none":null}`), &out)
		require.NoError(t, err)
		require.True(t, out.Some.IsSome())
		assert.EqualValues(t, 12, out.Some.Unwrap())
		assert.False(t, out.None.IsSome())
		assert.False(t, out.Absent.IsSome())
	})

	t.Run("invalid", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeByte(12)
		err := opt.UnmarshalJSON([]byte("{"))

		var syntaxErr *json.SyntaxError
		require.ErrorAs(t, err, &syntaxErr)
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})
}

func TestByte_MarshalYAML(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.SomeByte(12))
		require.NoError(t, err)
		assert.Equal(t, "12\n", string(data))
	})

	t.Run("some_as_inner_0", func(t *testing.T) {
		t.Parallel()

		expected, err := yaml.Marshal(byte(12))
		require.NoError(t, err)

		data, err := yaml.Marshal(option.SomeByte(12))
		require.NoError(t, err)
		assert.Equal(t, string(expected), string(data))
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.SomeByte(0))
		require.NoError(t, err)
		assert.Equal(t, "0\n", string(data))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.NoneByte())
		require.NoError(t, err)
		assert.Equal(t, "null\n", string(data))
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some    option.Byte `yaml:"some"`
			None    option.Byte `yaml:"none"`
			Omitted option.Byte `yaml:"omitted,omitempty"`
			Zero    option.Byte `yaml:"zero,omitempty"`
		}

		data, err := yaml.Marshal(wrapper{
			Some:    option.SomeByte(12),
			None:    option.NoneByte(),
			Omitted: option.NoneByte(),
			Zero:    option.SomeByte(0),
		})
		require.NoError(t, err)

		var fields map[string]any
		require.NoError(t, yaml.Unmarshal(data, &fields))
		assert.Contains(t, fields, "some")
		assert.NotNil(t, fields["some"])
		assert.Contains(t, fields, "none")
		assert.Nil(t, fields["none"])
		assert.NotContains(t, fields, "omitted")
		assert.Contains(t, fields, "zero")
		assert.NotNil(t, fields["zero"])
	})
}

func TestByte_UnmarshalYAML(t *testing.T) {
	t.Parallel()

	t.Run("roundtrip_0", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.SomeByte(12))
		require.NoError(t, err)

		var opt option.Byte
		require.NoError(t, yaml.Unmarshal(data, &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		var opt option.Byte
		require.NoError(t, yaml.Unmarshal([]byte("0\n"), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 0, opt.Unwrap())
	})

	t.Run("none_roundtrip", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.NoneByte())
		require.NoError(t, err)

		var opt option.Byte
		require.NoError(t, yaml.Unmarshal(data, &opt))
		assert.False(t, opt.IsSome())
	})

	t.Run("null_node_keeps_present_value", func(t *testing.T) {
		t.Parallel()

		// gopkg.in/yaml.v3 does not call UnmarshalYAML for a null node.
		opt := option.SomeByte(12)
		require.NoError(t, yaml.Unmarshal([]byte("null"), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("null_by_direct_call", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeByte(12)
		err := opt.UnmarshalYAML(func(v any) error {
			return yaml.Unmarshal([]byte("null"), v)
		})
		require.NoError(t, err)
		assert.False(t, opt.IsSome())
		assert.Zero(t, opt.Unwrap())
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some   option.Byte `yaml:"some"`
			Null   option.Byte `yaml:"nulled"`
			Tilde  option.Byte `yaml:"tilde"`
			Empty  option.Byte `yaml:"empty"`
			Absent option.Byte `yaml:"absent"`
		}

		some, err := yaml.Marshal(map[string]any{"some": option.SomeByte(12)})
		require.NoError(t, err)

		var out wrapper
		require.NoError(t, yaml.Unmarshal(append(some, []byte("nulled: null\ntilde: ~\nempty:\n")...), &out))
		require.True(t, out.Some.IsSome())
		assert.EqualValues(t, 12, out.Some.Unwrap())
		assert.False(t, out.Null.IsSome())
		assert.False(t, out.Tilde.IsSome())
		assert.False(t, out.Empty.IsSome())
		assert.False(t, out.Absent.IsSome())
	})

	t.Run("error", func(t *testing.T) {
		t.Parallel()

		errUnmarshal := errors.New("unmarshal failed")

		opt := option.SomeByte(12)
		err := opt.UnmarshalYAML(func(any) error {
			return errUnmarshal
		})
		require.ErrorIs(t, err, errUnmarshal)
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})
}

func ExampleByte_MarshalJSON() {
	for _, opt := range []option.Byte{option.SomeByte(12), option.NoneByte()} {
		data, err := json.Marshal(opt)
		if err != nil {
			fmt.Println("error:", err)

			return
		}

		fmt.Println(string(data))
	}
	// Output:
	// 12
	// null
}

func ExampleSomeByte() {
	opt := option.SomeByte(12)
	if opt.IsSome() {
		fmt.Println(opt.Unwrap())
	}
	// Output: 12
}

func ExampleNoneByte() {
	opt := option.NoneByte()
	if opt.IsZero() {
		fmt.Println("value is absent")
	}
	// Output: value is absent
}

func ExampleByte_IsSome() {
	some := option.SomeByte(12)
	none := option.NoneByte()
	fmt.Println(some.IsSome())
	fmt.Println(none.IsSome())
	// Output:
	// true
	// false
}

func ExampleByte_IsZero() {
	some := option.SomeByte(12)
	none := option.NoneByte()
	fmt.Println(some.IsZero())
	fmt.Println(none.IsZero())
	// Output:
	// false
	// true
}

func ExampleByte_IsNil() {
	some := option.SomeByte(12)
	none := option.NoneByte()
	fmt.Println(some.IsNil() == some.IsZero())
	fmt.Println(none.IsNil() == none.IsZero())
	// Output:
	// true
	// true
}

func ExampleByte_Get() {
	some := option.SomeByte(12)
	none := option.NoneByte()
	val, ok := some.Get()
	fmt.Println(val, ok)
	val, ok = none.Get()
	fmt.Println(val, ok)
	// Output:
	// 12 true
	// 0 false
}

func ExampleByte_MustGet() {
	some := option.SomeByte(12)
	fmt.Println(some.MustGet())
	// Output: 12
}

func ExampleByte_MustGet_panic() {
	none := option.NoneByte()
	eof := false
	defer func() {
		if !eof {
			fmt.Println("panic!", recover())
		}
	}()
	fmt.Println(none.MustGet())
	eof = true
	// Output: panic! optional value is not set
}

func ExampleByte_Unwrap() {
	some := option.SomeByte(12)
	none := option.NoneByte()
	fmt.Println(some.Unwrap())
	fmt.Println(none.Unwrap())
	// Output:
	// 12
	// 0
}

func ExampleByte_UnwrapOr() {
	some := option.SomeByte(12)
	none := option.NoneByte()
	fmt.Println(some.UnwrapOr(13))
	fmt.Println(none.UnwrapOr(13))
	// Output:
	// 12
	// 13
}

func ExampleByte_UnwrapOrElse() {
	some := option.SomeByte(12)
	none := option.NoneByte()
	fmt.Println(some.UnwrapOrElse(func() byte {
		return 13
	}))
	fmt.Println(none.UnwrapOrElse(func() byte {
		return 13
	}))
	// Output:
	// 12
	// 13
}
