// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"

	"github.com/tarantool/go-option"
)

func TestByte_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.True(t, someByte.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.False(t, emptyByte.IsSome())
	})
}

func TestByte_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.False(t, someByte.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.True(t, emptyByte.IsZero())
	})
}

func TestByte_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.False(t, someByte.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.True(t, emptyByte.IsNil())
	})
}

func TestByte_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		val, ok := someByte.Get()
		require.True(t, ok)
		assert.EqualValues(t, 12, val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		_, ok := emptyByte.Get()
		require.False(t, ok)
	})
}

func TestByte_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.EqualValues(t, 12, someByte.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.Panics(t, func() {
			emptyByte.MustGet()
		})
	})
}

func TestByte_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.EqualValues(t, 12, someByte.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.NotPanics(t, func() {
			emptyByte.Unwrap()
		})
	})
}

func TestByte_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.EqualValues(t, 12, someByte.UnwrapOr(13))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.EqualValues(t, 13, emptyByte.UnwrapOr(13))
	})
}

func TestByte_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.EqualValues(t, 12, someByte.UnwrapOrElse(func() byte {
			return 13
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.EqualValues(t, 13, emptyByte.UnwrapOrElse(func() byte {
			return 13
		}))
	})
}

func TestByte_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someByte := option.SomeByte(12)
		err := someByte.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Byte
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, 12, unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyByte := option.NoneByte()
		err := emptyByte.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Byte
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}

func ExampleSomeByte() {
	opt := option.SomeByte(12)
	if opt.IsSome() {
		fmt.Println(opt.Unwrap())
	}
	// Output: 12
}

func ExampleNoneByte() {
	opt := option.NoneByte()
	if opt.IsZero() {
		fmt.Println("value is absent")
	}
	// Output: value is absent
}

func ExampleByte_IsSome() {
	some := option.SomeByte(12)
	none := option.NoneByte()
	fmt.Println(some.IsSome())
	fmt.Println(none.IsSome())
	// Output:
	// true
	// false
}

func ExampleByte_IsZero() {
	some := option.SomeByte(12)
	none := option.NoneByte()
	fmt.Println(some.IsZero())
	fmt.Println(none.IsZero())
	// Output:
	// false
	// true
}

func ExampleByte_IsNil() {
	some := option.SomeByte(12)
	none := option.NoneByte()
	fmt.Println(some.IsNil() == some.IsZero())
	fmt.Println(none.IsNil() == none.IsZero())
	// Output:
	// true
	// true
}

func ExampleByte_Get() {
	some := option.SomeByte(12)
	none := option.NoneByte()
	val, ok := some.Get()
	fmt.Println(val, ok)
	val, ok = none.Get()
	fmt.Println(val, ok)
	// Output:
	// 12 true
	// 0 false
}

func ExampleByte_MustGet() {
	some := option.SomeByte(12)
	fmt.Println(some.MustGet())
	// Output: 12
}

func ExampleByte_MustGet_panic() {
	none := option.NoneByte()
	eof := false
	defer func() {
		if !eof {
			fmt.Println("panic!", recover())
		}
	}()
	fmt.Println(none.MustGet())
	eof = true
	// Output: panic! optional value is not set
}

func ExampleByte_Unwrap() {
	some := option.SomeByte(12)
	none := option.NoneByte()
	fmt.Println(some.Unwrap())
	fmt.Println(none.Unwrap())
	// Output:
	// 12
	// 0
}

func ExampleByte_UnwrapOr() {
	some := option.SomeByte(12)
	none := option.NoneByte()
	fmt.Println(some.UnwrapOr(13))
	fmt.Println(none.UnwrapOr(13))
	// Output:
	// 12
	// 13
}

func ExampleByte_UnwrapOrElse() {
	some := option.SomeByte(12)
	none := option.NoneByte()
	fmt.Println(some.UnwrapOrElse(func() byte {
		return 13
	}))
	fmt.Println(none.UnwrapOrElse(func() byte {
		return 13
	}))
	// Output:
	// 12
	// 13
}
