// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"

	"github.com/tarantool/go-option"
)

func TestByte_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.True(t, someByte.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.False(t, emptyByte.IsSome())
	})
}

func TestByte_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.False(t, someByte.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.True(t, emptyByte.IsZero())
	})
}

func TestByte_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.False(t, someByte.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.True(t, emptyByte.IsNil())
	})
}

func TestByte_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		val, ok := someByte.Get()
		require.True(t, ok)
		assert.EqualValues(t, 12, val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		_, ok := emptyByte.Get()
		require.False(t, ok)
	})
}

func TestByte_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.EqualValues(t, 12, someByte.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.Panics(t, func() {
			emptyByte.MustGet()
		})
	})
}

func TestByte_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.EqualValues(t, 12, someByte.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.NotPanics(t, func() {
			emptyByte.Unwrap()
		})
	})
}

func TestByte_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.EqualValues(t, 12, someByte.UnwrapOr(13))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.EqualValues(t, 13, emptyByte.UnwrapOr(13))
	})
}

func TestByte_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someByte := option.SomeByte(12)
		assert.EqualValues(t, 12, someByte.UnwrapOrElse(func() byte {
			return 13
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyByte := option.NoneByte()
		assert.EqualValues(t, 13, emptyByte.UnwrapOrElse(func() byte {
			return 13
		}))
	})
}

func TestByte_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someByte := option.SomeByte(12)
		err := someByte.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Byte
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, 12, unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyByte := option.NoneByte()
		err := emptyByte.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Byte
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}
