// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option

import (
	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"
)

// Bytes represents an optional value of type []byte.
// It can either hold a valid []byte (IsSome == true) or be empty (IsZero == true).
type Bytes struct {
	value  []byte
	exists bool
}

var _ commonInterface[[]byte] = (*Bytes)(nil)

// SomeBytes creates an optional Bytes with the given []byte value.
// The returned Bytes will have IsSome() == true and IsZero() == false.
//
// Example:
//
//	o := SomeBytes([]byte("hello"))
//	if o.IsSome() {
//	    v := o.Unwrap() // v == []byte("hello")
//	}
func SomeBytes(value []byte) Bytes {
	return Bytes{
		value:  value,
		exists: true,
	}
}

// NoneBytes creates an empty optional Bytes value.
// The returned Bytes will have IsSome() == false and IsZero() == true.
//
// Example:
//
//	o := NoneBytes()
//	if o.IsZero() {
//	    fmt.Println("value is absent")
//	}
func NoneBytes() Bytes {
	return Bytes{
		exists: false,
		value:  zero[[]byte](),
	}
}

// IsSome returns true if the Bytes contains a value.
// This indicates the value is explicitly set (not None).
func (o Bytes) IsSome() bool {
	return o.exists
}

// IsZero returns true if the Bytes does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o Bytes) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o Bytes) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of []byte, false).
//
// Recommended usage:
//
//	if value, ok := o.Get(); ok {
//	    // use value
//	}
func (o Bytes) Get() ([]byte, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o Bytes) MustGet() []byte {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for []byte.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o Bytes) Unwrap() []byte {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
//
// Example:
//
//	o := NoneBytes()
//	v := o.UnwrapOr(someDefaultBytes)
func (o Bytes) UnwrapOr(defaultValue []byte) []byte {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
//
// Example:
//
//	o := NoneBytes()
//	v := o.UnwrapOrElse(func() []byte { return computeDefault() })
func (o Bytes) UnwrapOrElse(defaultValue func() []byte) []byte {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

// EncodeMsgpack encodes the Bytes value using MessagePack format.
// - If the value is present, it is encoded as []byte.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o Bytes) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return newEncodeError("Bytes", encodeBytes(encoder, o.value))
	}

	return newEncodeError("Bytes", encoder.EncodeNil())
}

// DecodeMsgpack decodes a Bytes value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneBytes)
//   - []byte: interpreted as a present value (SomeBytes)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on []byte: exists = true, value = decoded value
func (o *Bytes) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return newDecodeError("Bytes", err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return newDecodeError("Bytes", decoder.Skip())
	case checkBytes(code):
		o.value, err = decodeBytes(decoder)
		if err != nil {
			return newDecodeError("Bytes", err)
		}
		o.exists = true

		return err
	default:
		return newDecodeWithCodeError("Bytes", code)
	}
}
