// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option

import (
	"bytes"
	"encoding/json"

	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"
)

// Bytes represents an optional value of type []byte.
// It can either hold a valid []byte (IsSome == true) or be empty (IsZero == true).
type Bytes struct {
	value  []byte
	exists bool
}

var _ commonInterface[[]byte] = (*Bytes)(nil)

// SomeBytes creates an optional Bytes with the given []byte value.
// The returned Bytes will have IsSome() == true and IsZero() == false.
func SomeBytes(value []byte) Bytes {
	return Bytes{
		value:  value,
		exists: true,
	}
}

// NoneBytes creates an empty optional Bytes value.
// The returned Bytes will have IsSome() == false and IsZero() == true.
func NoneBytes() Bytes {
	return Bytes{
		exists: false,
		value:  zero[[]byte](),
	}
}

// IsSome returns true if the Bytes contains a value.
// This indicates the value is explicitly set (not None).
func (o Bytes) IsSome() bool {
	return o.exists
}

// IsZero returns true if the Bytes does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o Bytes) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o Bytes) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of []byte, false).
//
// Recommended usage:
//
//	if value, ok := o.Get(); ok {
//	    // use value
//	}
func (o Bytes) Get() ([]byte, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o Bytes) MustGet() []byte {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for []byte.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o Bytes) Unwrap() []byte {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
func (o Bytes) UnwrapOr(defaultValue []byte) []byte {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
func (o Bytes) UnwrapOrElse(defaultValue func() []byte) []byte {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

// EncodeMsgpack encodes the Bytes value using MessagePack format.
// - If the value is present, it is encoded as []byte.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o Bytes) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return newEncodeError("Bytes", encodeBytes(encoder, o.value))
	}

	return newEncodeError("Bytes", encoder.EncodeNil())
}

// DecodeMsgpack decodes a Bytes value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneBytes)
//   - []byte: interpreted as a present value (SomeBytes)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on []byte: exists = true, value = decoded value
func (o *Bytes) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return newDecodeError("Bytes", err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return newDecodeError("Bytes", decoder.Skip())
	case checkBytes(code):
		o.value, err = decodeBytes(decoder)
		if err != nil {
			return newDecodeError("Bytes", err)
		}
		o.exists = true

		return err
	default:
		return newDecodeWithCodeError("Bytes", code)
	}
}

// MarshalJSON implements the json.Marshaler interface.
//   - If the value is present, it is encoded exactly as json.Marshal encodes
//     the []byte value itself.
//   - If the value is absent (None), it is encoded as JSON null.
//
// A present nil []byte is encoded as JSON null too, so it decodes back
// as an absent value.
//
// A struct field of type Bytes with the "omitzero" JSON tag option is
// omitted when the value is absent, since IsZero reports absence.
// The "omitempty" option has no effect on it.
func (o Bytes) MarshalJSON() ([]byte, error) {
	if !o.exists {
		return []byte("null"), nil
	}

	return json.Marshal(&o.value)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
//   - JSON null is decoded as no value (NoneBytes).
//   - Any other JSON value is decoded as []byte and stored as a present value.
//
// An error of decoding []byte is returned unchanged, and the receiver
// is left intact.
func (o *Bytes) UnmarshalJSON(data []byte) error {
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		*o = NoneBytes()

		return nil
	}

	var value []byte

	err := json.Unmarshal(data, &value)
	if err != nil {
		return err
	}

	*o = SomeBytes(value)

	return nil
}

// MarshalYAML implements the Marshaler interface of gopkg.in/yaml.v3
// (and yaml.v2) without depending on it.
//   - If the value is present, it returns a pointer to it, so the value is
//     encoded exactly as the YAML encoder encodes []byte itself.
//   - If the value is absent (None), it returns nil, which is encoded as null.
//
// A struct field of type Bytes with the "omitempty" YAML tag option is
// omitted when the value is absent, since the encoder consults IsZero.
func (o Bytes) MarshalYAML() (any, error) {
	if !o.exists {
		return nil, nil
	}

	return &o.value, nil
}

// UnmarshalYAML implements the obsolete Unmarshaler interface of
// gopkg.in/yaml.v3 (the only one of yaml.v2) without depending on it.
//   - A null value is decoded as no value (NoneBytes).
//   - Any other value is decoded as []byte and stored as a present value.
//
// gopkg.in/yaml.v3 never calls this method for a null node (null, ~ or an
// empty value): it leaves the receiver unchanged. Decoding null into a zero
// Bytes therefore yields None, but decoding it into a present value
// keeps that value.
//
// An error of decoding []byte is returned unchanged, and the receiver
// is left intact.
func (o *Bytes) UnmarshalYAML(unmarshal func(any) error) error {
	var value *[]byte

	err := unmarshal(&value)
	if err != nil {
		return err
	}

	if value == nil {
		*o = NoneBytes()

		return nil
	}

	*o = SomeBytes(*value)

	return nil
}
