// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option

import (
	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"
)

// Byte represents an optional value of type byte.
// It can either hold a valid byte (IsSome == true) or be empty (IsZero == true).
type Byte struct {
	value  byte
	exists bool
}

var _ commonInterface[byte] = (*Byte)(nil)

// SomeByte creates an optional Byte with the given byte value.
// The returned Byte will have IsSome() == true and IsZero() == false.
//
// Example:
//
//	o := SomeByte(12)
//	if o.IsSome() {
//	    v := o.Unwrap() // v == 12
//	}
func SomeByte(value byte) Byte {
	return Byte{
		value:  value,
		exists: true,
	}
}

// NoneByte creates an empty optional Byte value.
// The returned Byte will have IsSome() == false and IsZero() == true.
//
// Example:
//
//	o := NoneByte()
//	if o.IsZero() {
//	    fmt.Println("value is absent")
//	}
func NoneByte() Byte {
	return Byte{
		exists: false,
		value:  zero[byte](),
	}
}

// IsSome returns true if the Byte contains a value.
// This indicates the value is explicitly set (not None).
func (o Byte) IsSome() bool {
	return o.exists
}

// IsZero returns true if the Byte does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o Byte) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o Byte) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of byte, false).
//
// Recommended usage:
//
//	if value, ok := o.Get(); ok {
//	    // use value
//	}
func (o Byte) Get() (byte, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o Byte) MustGet() byte {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for byte.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o Byte) Unwrap() byte {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
//
// Example:
//
//	o := NoneByte()
//	v := o.UnwrapOr(someDefaultByte)
func (o Byte) UnwrapOr(defaultValue byte) byte {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
//
// Example:
//
//	o := NoneByte()
//	v := o.UnwrapOrElse(func() byte { return computeDefault() })
func (o Byte) UnwrapOrElse(defaultValue func() byte) byte {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

// EncodeMsgpack encodes the Byte value using MessagePack format.
// - If the value is present, it is encoded as byte.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o Byte) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return newEncodeError("Byte", encodeByte(encoder, o.value))
	}

	return newEncodeError("Byte", encoder.EncodeNil())
}

// DecodeMsgpack decodes a Byte value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneByte)
//   - byte: interpreted as a present value (SomeByte)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on byte: exists = true, value = decoded value
func (o *Byte) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return newDecodeError("Byte", err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return newDecodeError("Byte", decoder.Skip())
	case checkNumber(code):
		o.value, err = decodeByte(decoder)
		if err != nil {
			return newDecodeError("Byte", err)
		}
		o.exists = true

		return err
	default:
		return newDecodeWithCodeError("Byte", code)
	}
}
