// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"
	"gopkg.in/yaml.v3"

	"github.com/tarantool/go-option"
)

func TestFloat64_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someFloat64 := option.SomeFloat64(12)
		assert.True(t, someFloat64.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyFloat64 := option.NoneFloat64()
		assert.False(t, emptyFloat64.IsSome())
	})
}

func TestFloat64_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someFloat64 := option.SomeFloat64(12)
		assert.False(t, someFloat64.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyFloat64 := option.NoneFloat64()
		assert.True(t, emptyFloat64.IsZero())
	})
}

func TestFloat64_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someFloat64 := option.SomeFloat64(12)
		assert.False(t, someFloat64.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyFloat64 := option.NoneFloat64()
		assert.True(t, emptyFloat64.IsNil())
	})
}

func TestFloat64_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someFloat64 := option.SomeFloat64(12)
		val, ok := someFloat64.Get()
		require.True(t, ok)
		assert.EqualValues(t, 12, val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyFloat64 := option.NoneFloat64()
		_, ok := emptyFloat64.Get()
		require.False(t, ok)
	})
}

func TestFloat64_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someFloat64 := option.SomeFloat64(12)
		assert.EqualValues(t, 12, someFloat64.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyFloat64 := option.NoneFloat64()
		assert.Panics(t, func() {
			emptyFloat64.MustGet()
		})
	})
}

func TestFloat64_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someFloat64 := option.SomeFloat64(12)
		assert.EqualValues(t, 12, someFloat64.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyFloat64 := option.NoneFloat64()
		assert.NotPanics(t, func() {
			emptyFloat64.Unwrap()
		})
	})
}

func TestFloat64_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someFloat64 := option.SomeFloat64(12)
		assert.EqualValues(t, 12, someFloat64.UnwrapOr(13))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyFloat64 := option.NoneFloat64()
		assert.EqualValues(t, 13, emptyFloat64.UnwrapOr(13))
	})
}

func TestFloat64_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someFloat64 := option.SomeFloat64(12)
		assert.EqualValues(t, 12, someFloat64.UnwrapOrElse(func() float64 {
			return 13
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyFloat64 := option.NoneFloat64()
		assert.EqualValues(t, 13, emptyFloat64.UnwrapOrElse(func() float64 {
			return 13
		}))
	})
}

func TestFloat64_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someFloat64 := option.SomeFloat64(12)
		err := someFloat64.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Float64
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, 12, unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyFloat64 := option.NoneFloat64()
		err := emptyFloat64.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Float64
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}

func TestFloat64_MarshalJSON(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.SomeFloat64(12))
		require.NoError(t, err)
		assert.Equal(t, `12`, string(data))
	})

	t.Run("some_as_inner_0", func(t *testing.T) {
		t.Parallel()

		expected, err := json.Marshal(float64(12))
		require.NoError(t, err)

		data, err := json.Marshal(option.SomeFloat64(12))
		require.NoError(t, err)
		assert.Equal(t, string(expected), string(data))
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.SomeFloat64(0))
		require.NoError(t, err)
		assert.Equal(t, `0`, string(data))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.NoneFloat64())
		require.NoError(t, err)
		assert.Equal(t, "null", string(data))
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some option.Float64 `json:"some"`
			None option.Float64 `json:"none"`
		}

		data, err := json.Marshal(wrapper{
			Some: option.SomeFloat64(12),
			None: option.NoneFloat64(),
		})
		require.NoError(t, err)
		assert.Equal(t, `{"some":12,"none":null}`, string(data))
	})

	t.Run("omitzero", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Value option.Float64 `json:"value,omitzero"`
		}

		data, err := json.Marshal(wrapper{Value: option.NoneFloat64()})
		require.NoError(t, err)
		assert.Equal(t, "{}", string(data))

		data, err = json.Marshal(wrapper{Value: option.SomeFloat64(0)})
		require.NoError(t, err)
		assert.Equal(t, `{"value":0}`, string(data))
	})
}

func TestFloat64_UnmarshalJSON(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var opt option.Float64
		require.NoError(t, json.Unmarshal([]byte(`12`), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("roundtrip_0", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.SomeFloat64(12))
		require.NoError(t, err)

		var opt option.Float64
		require.NoError(t, json.Unmarshal(data, &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		var opt option.Float64
		require.NoError(t, json.Unmarshal([]byte(`0`), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 0, opt.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeFloat64(12)
		require.NoError(t, json.Unmarshal([]byte("null"), &opt))
		assert.False(t, opt.IsSome())
		assert.Zero(t, opt.Unwrap())
	})

	t.Run("none_with_spaces", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeFloat64(12)
		require.NoError(t, opt.UnmarshalJSON([]byte(" null\n")))
		assert.False(t, opt.IsSome())
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some   option.Float64 `json:"some"`
			None   option.Float64 `json:"none"`
			Absent option.Float64 `json:"absent"`
		}

		var out wrapper
		err := json.Unmarshal([]byte(`{"some":12,"none":null}`), &out)
		require.NoError(t, err)
		require.True(t, out.Some.IsSome())
		assert.EqualValues(t, 12, out.Some.Unwrap())
		assert.False(t, out.None.IsSome())
		assert.False(t, out.Absent.IsSome())
	})

	t.Run("invalid", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeFloat64(12)
		err := opt.UnmarshalJSON([]byte("{"))

		var syntaxErr *json.SyntaxError
		require.ErrorAs(t, err, &syntaxErr)
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})
}

func TestFloat64_MarshalYAML(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.SomeFloat64(12))
		require.NoError(t, err)
		assert.Equal(t, "12\n", string(data))
	})

	t.Run("some_as_inner_0", func(t *testing.T) {
		t.Parallel()

		expected, err := yaml.Marshal(float64(12))
		require.NoError(t, err)

		data, err := yaml.Marshal(option.SomeFloat64(12))
		require.NoError(t, err)
		assert.Equal(t, string(expected), string(data))
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.SomeFloat64(0))
		require.NoError(t, err)
		assert.Equal(t, "0\n", string(data))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.NoneFloat64())
		require.NoError(t, err)
		assert.Equal(t, "null\n", string(data))
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some    option.Float64 `yaml:"some"`
			None    option.Float64 `yaml:"none"`
			Omitted option.Float64 `yaml:"omitted,omitempty"`
			Zero    option.Float64 `yaml:"zero,omitempty"`
		}

		data, err := yaml.Marshal(wrapper{
			Some:    option.SomeFloat64(12),
			None:    option.NoneFloat64(),
			Omitted: option.NoneFloat64(),
			Zero:    option.SomeFloat64(0),
		})
		require.NoError(t, err)

		var fields map[string]any
		require.NoError(t, yaml.Unmarshal(data, &fields))
		assert.Contains(t, fields, "some")
		assert.NotNil(t, fields["some"])
		assert.Contains(t, fields, "none")
		assert.Nil(t, fields["none"])
		assert.NotContains(t, fields, "omitted")
		assert.Contains(t, fields, "zero")
		assert.NotNil(t, fields["zero"])
	})
}

func TestFloat64_UnmarshalYAML(t *testing.T) {
	t.Parallel()

	t.Run("roundtrip_0", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.SomeFloat64(12))
		require.NoError(t, err)

		var opt option.Float64
		require.NoError(t, yaml.Unmarshal(data, &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		var opt option.Float64
		require.NoError(t, yaml.Unmarshal([]byte("0\n"), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 0, opt.Unwrap())
	})

	t.Run("none_roundtrip", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.NoneFloat64())
		require.NoError(t, err)

		var opt option.Float64
		require.NoError(t, yaml.Unmarshal(data, &opt))
		assert.False(t, opt.IsSome())
	})

	t.Run("null_node_keeps_present_value", func(t *testing.T) {
		t.Parallel()

		// gopkg.in/yaml.v3 does not call UnmarshalYAML for a null node.
		opt := option.SomeFloat64(12)
		require.NoError(t, yaml.Unmarshal([]byte("null"), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("null_by_direct_call", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeFloat64(12)
		err := opt.UnmarshalYAML(func(v any) error {
			return yaml.Unmarshal([]byte("null"), v)
		})
		require.NoError(t, err)
		assert.False(t, opt.IsSome())
		assert.Zero(t, opt.Unwrap())
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some   option.Float64 `yaml:"some"`
			Null   option.Float64 `yaml:"nulled"`
			Tilde  option.Float64 `yaml:"tilde"`
			Empty  option.Float64 `yaml:"empty"`
			Absent option.Float64 `yaml:"absent"`
		}

		some, err := yaml.Marshal(map[string]any{"some": option.SomeFloat64(12)})
		require.NoError(t, err)

		var out wrapper
		require.NoError(t, yaml.Unmarshal(append(some, []byte("nulled: null\ntilde: ~\nempty:\n")...), &out))
		require.True(t, out.Some.IsSome())
		assert.EqualValues(t, 12, out.Some.Unwrap())
		assert.False(t, out.Null.IsSome())
		assert.False(t, out.Tilde.IsSome())
		assert.False(t, out.Empty.IsSome())
		assert.False(t, out.Absent.IsSome())
	})

	t.Run("error", func(t *testing.T) {
		t.Parallel()

		errUnmarshal := errors.New("unmarshal failed")

		opt := option.SomeFloat64(12)
		err := opt.UnmarshalYAML(func(any) error {
			return errUnmarshal
		})
		require.ErrorIs(t, err, errUnmarshal)
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})
}

func ExampleFloat64_MarshalJSON() {
	for _, opt := range []option.Float64{option.SomeFloat64(12), option.NoneFloat64()} {
		data, err := json.Marshal(opt)
		if err != nil {
			fmt.Println("error:", err)

			return
		}

		fmt.Println(string(data))
	}
	// Output:
	// 12
	// null
}

func ExampleSomeFloat64() {
	opt := option.SomeFloat64(12)
	if opt.IsSome() {
		fmt.Println(opt.Unwrap())
	}
	// Output: 12
}

func ExampleNoneFloat64() {
	opt := option.NoneFloat64()
	if opt.IsZero() {
		fmt.Println("value is absent")
	}
	// Output: value is absent
}

func ExampleFloat64_IsSome() {
	some := option.SomeFloat64(12)
	none := option.NoneFloat64()
	fmt.Println(some.IsSome())
	fmt.Println(none.IsSome())
	// Output:
	// true
	// false
}

func ExampleFloat64_IsZero() {
	some := option.SomeFloat64(12)
	none := option.NoneFloat64()
	fmt.Println(some.IsZero())
	fmt.Println(none.IsZero())
	// Output:
	// false
	// true
}

func ExampleFloat64_IsNil() {
	some := option.SomeFloat64(12)
	none := option.NoneFloat64()
	fmt.Println(some.IsNil() == some.IsZero())
	fmt.Println(none.IsNil() == none.IsZero())
	// Output:
	// true
	// true
}

func ExampleFloat64_Get() {
	some := option.SomeFloat64(12)
	none := option.NoneFloat64()
	val, ok := some.Get()
	fmt.Println(val, ok)
	val, ok = none.Get()
	fmt.Println(val, ok)
	// Output:
	// 12 true
	// 0 false
}

func ExampleFloat64_MustGet() {
	some := option.SomeFloat64(12)
	fmt.Println(some.MustGet())
	// Output: 12
}

func ExampleFloat64_MustGet_panic() {
	none := option.NoneFloat64()
	eof := false
	defer func() {
		if !eof {
			fmt.Println("panic!", recover())
		}
	}()
	fmt.Println(none.MustGet())
	eof = true
	// Output: panic! optional value is not set
}

func ExampleFloat64_Unwrap() {
	some := option.SomeFloat64(12)
	none := option.NoneFloat64()
	fmt.Println(some.Unwrap())
	fmt.Println(none.Unwrap())
	// Output:
	// 12
	// 0
}

func ExampleFloat64_UnwrapOr() {
	some := option.SomeFloat64(12)
	none := option.NoneFloat64()
	fmt.Println(some.UnwrapOr(13))
	fmt.Println(none.UnwrapOr(13))
	// Output:
	// 12
	// 13
}

func ExampleFloat64_UnwrapOrElse() {
	some := option.SomeFloat64(12)
	none := option.NoneFloat64()
	fmt.Println(some.UnwrapOrElse(func() float64 {
		return 13
	}))
	fmt.Println(none.UnwrapOrElse(func() float64 {
		return 13
	}))
	// Output:
	// 12
	// 13
}
