// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option

import (
	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"
)

// Float64 represents an optional value of type float64.
// It can either hold a valid float64 (IsSome == true) or be empty (IsZero == true).
type Float64 struct {
	value  float64
	exists bool
}

var _ commonInterface[float64] = (*Float64)(nil)

// SomeFloat64 creates an optional Float64 with the given float64 value.
// The returned Float64 will have IsSome() == true and IsZero() == false.
//
// Example:
//
//	o := SomeFloat64(12)
//	if o.IsSome() {
//	    v := o.Unwrap() // v == 12
//	}
func SomeFloat64(value float64) Float64 {
	return Float64{
		value:  value,
		exists: true,
	}
}

// NoneFloat64 creates an empty optional Float64 value.
// The returned Float64 will have IsSome() == false and IsZero() == true.
//
// Example:
//
//	o := NoneFloat64()
//	if o.IsZero() {
//	    fmt.Println("value is absent")
//	}
func NoneFloat64() Float64 {
	return Float64{
		exists: false,
		value:  zero[float64](),
	}
}

// IsSome returns true if the Float64 contains a value.
// This indicates the value is explicitly set (not None).
func (o Float64) IsSome() bool {
	return o.exists
}

// IsZero returns true if the Float64 does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o Float64) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o Float64) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of float64, false).
//
// Recommended usage:
//
//	if value, ok := o.Get(); ok {
//	    // use value
//	}
func (o Float64) Get() (float64, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o Float64) MustGet() float64 {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for float64.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o Float64) Unwrap() float64 {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
//
// Example:
//
//	o := NoneFloat64()
//	v := o.UnwrapOr(someDefaultFloat64)
func (o Float64) UnwrapOr(defaultValue float64) float64 {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
//
// Example:
//
//	o := NoneFloat64()
//	v := o.UnwrapOrElse(func() float64 { return computeDefault() })
func (o Float64) UnwrapOrElse(defaultValue func() float64) float64 {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

// EncodeMsgpack encodes the Float64 value using MessagePack format.
// - If the value is present, it is encoded as float64.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o Float64) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return newEncodeError("Float64", encodeFloat64(encoder, o.value))
	}

	return newEncodeError("Float64", encoder.EncodeNil())
}

// DecodeMsgpack decodes a Float64 value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneFloat64)
//   - float64: interpreted as a present value (SomeFloat64)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on float64: exists = true, value = decoded value
func (o *Float64) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return newDecodeError("Float64", err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return newDecodeError("Float64", decoder.Skip())
	case checkFloat(code):
		o.value, err = decodeFloat64(decoder)
		if err != nil {
			return newDecodeError("Float64", err)
		}
		o.exists = true

		return err
	default:
		return newDecodeWithCodeError("Float64", code)
	}
}
