// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"

	"github.com/tarantool/go-option"
)

func TestFloat64_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someFloat64 := option.SomeFloat64(12)
		assert.True(t, someFloat64.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyFloat64 := option.NoneFloat64()
		assert.False(t, emptyFloat64.IsSome())
	})
}

func TestFloat64_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someFloat64 := option.SomeFloat64(12)
		assert.False(t, someFloat64.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyFloat64 := option.NoneFloat64()
		assert.True(t, emptyFloat64.IsZero())
	})
}

func TestFloat64_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someFloat64 := option.SomeFloat64(12)
		assert.False(t, someFloat64.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyFloat64 := option.NoneFloat64()
		assert.True(t, emptyFloat64.IsNil())
	})
}

func TestFloat64_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someFloat64 := option.SomeFloat64(12)
		val, ok := someFloat64.Get()
		require.True(t, ok)
		assert.EqualValues(t, 12, val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyFloat64 := option.NoneFloat64()
		_, ok := emptyFloat64.Get()
		require.False(t, ok)
	})
}

func TestFloat64_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someFloat64 := option.SomeFloat64(12)
		assert.EqualValues(t, 12, someFloat64.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyFloat64 := option.NoneFloat64()
		assert.Panics(t, func() {
			emptyFloat64.MustGet()
		})
	})
}

func TestFloat64_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someFloat64 := option.SomeFloat64(12)
		assert.EqualValues(t, 12, someFloat64.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyFloat64 := option.NoneFloat64()
		assert.NotPanics(t, func() {
			emptyFloat64.Unwrap()
		})
	})
}

func TestFloat64_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someFloat64 := option.SomeFloat64(12)
		assert.EqualValues(t, 12, someFloat64.UnwrapOr(13))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyFloat64 := option.NoneFloat64()
		assert.EqualValues(t, 13, emptyFloat64.UnwrapOr(13))
	})
}

func TestFloat64_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someFloat64 := option.SomeFloat64(12)
		assert.EqualValues(t, 12, someFloat64.UnwrapOrElse(func() float64 {
			return 13
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyFloat64 := option.NoneFloat64()
		assert.EqualValues(t, 13, emptyFloat64.UnwrapOrElse(func() float64 {
			return 13
		}))
	})
}

func TestFloat64_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someFloat64 := option.SomeFloat64(12)
		err := someFloat64.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Float64
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, 12, unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyFloat64 := option.NoneFloat64()
		err := emptyFloat64.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Float64
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}
