// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option

import (
	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"
)

// Float32 represents an optional value of type float32.
// It can either hold a valid float32 (IsSome == true) or be empty (IsZero == true).
type Float32 struct {
	value  float32
	exists bool
}

var _ commonInterface[float32] = (*Float32)(nil)

// SomeFloat32 creates an optional Float32 with the given float32 value.
// The returned Float32 will have IsSome() == true and IsZero() == false.
func SomeFloat32(value float32) Float32 {
	return Float32{
		value:  value,
		exists: true,
	}
}

// NoneFloat32 creates an empty optional Float32 value.
// The returned Float32 will have IsSome() == false and IsZero() == true.
func NoneFloat32() Float32 {
	return Float32{
		exists: false,
		value:  zero[float32](),
	}
}

// IsSome returns true if the Float32 contains a value.
// This indicates the value is explicitly set (not None).
func (o Float32) IsSome() bool {
	return o.exists
}

// IsZero returns true if the Float32 does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o Float32) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o Float32) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of float32, false).
//
// Recommended usage:
//
//	if value, ok := o.Get(); ok {
//	    // use value
//	}
func (o Float32) Get() (float32, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o Float32) MustGet() float32 {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for float32.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o Float32) Unwrap() float32 {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
func (o Float32) UnwrapOr(defaultValue float32) float32 {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
func (o Float32) UnwrapOrElse(defaultValue func() float32) float32 {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

// EncodeMsgpack encodes the Float32 value using MessagePack format.
// - If the value is present, it is encoded as float32.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o Float32) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return newEncodeError("Float32", encodeFloat32(encoder, o.value))
	}

	return newEncodeError("Float32", encoder.EncodeNil())
}

// DecodeMsgpack decodes a Float32 value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneFloat32)
//   - float32: interpreted as a present value (SomeFloat32)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on float32: exists = true, value = decoded value
func (o *Float32) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return newDecodeError("Float32", err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return newDecodeError("Float32", decoder.Skip())
	case checkFloat(code):
		o.value, err = decodeFloat32(decoder)
		if err != nil {
			return newDecodeError("Float32", err)
		}
		o.exists = true

		return err
	default:
		return newDecodeWithCodeError("Float32", code)
	}
}
