// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"

	"github.com/tarantool/go-option"
)

func TestInt16_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt16 := option.SomeInt16(12)
		assert.True(t, someInt16.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt16 := option.NoneInt16()
		assert.False(t, emptyInt16.IsSome())
	})
}

func TestInt16_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt16 := option.SomeInt16(12)
		assert.False(t, someInt16.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt16 := option.NoneInt16()
		assert.True(t, emptyInt16.IsZero())
	})
}

func TestInt16_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt16 := option.SomeInt16(12)
		assert.False(t, someInt16.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt16 := option.NoneInt16()
		assert.True(t, emptyInt16.IsNil())
	})
}

func TestInt16_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt16 := option.SomeInt16(12)
		val, ok := someInt16.Get()
		require.True(t, ok)
		assert.EqualValues(t, 12, val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt16 := option.NoneInt16()
		_, ok := emptyInt16.Get()
		require.False(t, ok)
	})
}

func TestInt16_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt16 := option.SomeInt16(12)
		assert.EqualValues(t, 12, someInt16.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt16 := option.NoneInt16()
		assert.Panics(t, func() {
			emptyInt16.MustGet()
		})
	})
}

func TestInt16_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt16 := option.SomeInt16(12)
		assert.EqualValues(t, 12, someInt16.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt16 := option.NoneInt16()
		assert.NotPanics(t, func() {
			emptyInt16.Unwrap()
		})
	})
}

func TestInt16_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt16 := option.SomeInt16(12)
		assert.EqualValues(t, 12, someInt16.UnwrapOr(13))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt16 := option.NoneInt16()
		assert.EqualValues(t, 13, emptyInt16.UnwrapOr(13))
	})
}

func TestInt16_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt16 := option.SomeInt16(12)
		assert.EqualValues(t, 12, someInt16.UnwrapOrElse(func() int16 {
			return 13
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt16 := option.NoneInt16()
		assert.EqualValues(t, 13, emptyInt16.UnwrapOrElse(func() int16 {
			return 13
		}))
	})
}

func TestInt16_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someInt16 := option.SomeInt16(12)
		err := someInt16.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Int16
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, 12, unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyInt16 := option.NoneInt16()
		err := emptyInt16.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Int16
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}

func ExampleSomeInt16() {
	opt := option.SomeInt16(12)
	if opt.IsSome() {
		fmt.Println(opt.Unwrap())
	}
	// Output: 12
}

func ExampleNoneInt16() {
	opt := option.NoneInt16()
	if opt.IsZero() {
		fmt.Println("value is absent")
	}
	// Output: value is absent
}

func ExampleInt16_IsSome() {
	some := option.SomeInt16(12)
	none := option.NoneInt16()
	fmt.Println(some.IsSome())
	fmt.Println(none.IsSome())
	// Output:
	// true
	// false
}

func ExampleInt16_IsZero() {
	some := option.SomeInt16(12)
	none := option.NoneInt16()
	fmt.Println(some.IsZero())
	fmt.Println(none.IsZero())
	// Output:
	// false
	// true
}

func ExampleInt16_IsNil() {
	some := option.SomeInt16(12)
	none := option.NoneInt16()
	fmt.Println(some.IsNil() == some.IsZero())
	fmt.Println(none.IsNil() == none.IsZero())
	// Output:
	// true
	// true
}

func ExampleInt16_Get() {
	some := option.SomeInt16(12)
	none := option.NoneInt16()
	val, ok := some.Get()
	fmt.Println(val, ok)
	val, ok = none.Get()
	fmt.Println(val, ok)
	// Output:
	// 12 true
	// 0 false
}

func ExampleInt16_MustGet() {
	some := option.SomeInt16(12)
	fmt.Println(some.MustGet())
	// Output: 12
}

func ExampleInt16_MustGet_panic() {
	none := option.NoneInt16()
	eof := false
	defer func() {
		if !eof {
			fmt.Println("panic!", recover())
		}
	}()
	fmt.Println(none.MustGet())
	eof = true
	// Output: panic! optional value is not set
}

func ExampleInt16_Unwrap() {
	some := option.SomeInt16(12)
	none := option.NoneInt16()
	fmt.Println(some.Unwrap())
	fmt.Println(none.Unwrap())
	// Output:
	// 12
	// 0
}

func ExampleInt16_UnwrapOr() {
	some := option.SomeInt16(12)
	none := option.NoneInt16()
	fmt.Println(some.UnwrapOr(13))
	fmt.Println(none.UnwrapOr(13))
	// Output:
	// 12
	// 13
}

func ExampleInt16_UnwrapOrElse() {
	some := option.SomeInt16(12)
	none := option.NoneInt16()
	fmt.Println(some.UnwrapOrElse(func() int16 {
		return 13
	}))
	fmt.Println(none.UnwrapOrElse(func() int16 {
		return 13
	}))
	// Output:
	// 12
	// 13
}
