// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"

	"github.com/tarantool/go-option"
)

func TestInt16_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt16 := option.SomeInt16(12)
		assert.True(t, someInt16.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt16 := option.NoneInt16()
		assert.False(t, emptyInt16.IsSome())
	})
}

func TestInt16_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt16 := option.SomeInt16(12)
		assert.False(t, someInt16.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt16 := option.NoneInt16()
		assert.True(t, emptyInt16.IsZero())
	})
}

func TestInt16_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt16 := option.SomeInt16(12)
		assert.False(t, someInt16.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt16 := option.NoneInt16()
		assert.True(t, emptyInt16.IsNil())
	})
}

func TestInt16_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt16 := option.SomeInt16(12)
		val, ok := someInt16.Get()
		require.True(t, ok)
		assert.EqualValues(t, 12, val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt16 := option.NoneInt16()
		_, ok := emptyInt16.Get()
		require.False(t, ok)
	})
}

func TestInt16_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt16 := option.SomeInt16(12)
		assert.EqualValues(t, 12, someInt16.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt16 := option.NoneInt16()
		assert.Panics(t, func() {
			emptyInt16.MustGet()
		})
	})
}

func TestInt16_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt16 := option.SomeInt16(12)
		assert.EqualValues(t, 12, someInt16.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt16 := option.NoneInt16()
		assert.NotPanics(t, func() {
			emptyInt16.Unwrap()
		})
	})
}

func TestInt16_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt16 := option.SomeInt16(12)
		assert.EqualValues(t, 12, someInt16.UnwrapOr(13))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt16 := option.NoneInt16()
		assert.EqualValues(t, 13, emptyInt16.UnwrapOr(13))
	})
}

func TestInt16_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt16 := option.SomeInt16(12)
		assert.EqualValues(t, 12, someInt16.UnwrapOrElse(func() int16 {
			return 13
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt16 := option.NoneInt16()
		assert.EqualValues(t, 13, emptyInt16.UnwrapOrElse(func() int16 {
			return 13
		}))
	})
}

func TestInt16_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someInt16 := option.SomeInt16(12)
		err := someInt16.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Int16
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, 12, unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyInt16 := option.NoneInt16()
		err := emptyInt16.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Int16
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}
