// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"

	"github.com/tarantool/go-option"
)

func TestInt32_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt32 := option.SomeInt32(12)
		assert.True(t, someInt32.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt32 := option.NoneInt32()
		assert.False(t, emptyInt32.IsSome())
	})
}

func TestInt32_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt32 := option.SomeInt32(12)
		assert.False(t, someInt32.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt32 := option.NoneInt32()
		assert.True(t, emptyInt32.IsZero())
	})
}

func TestInt32_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt32 := option.SomeInt32(12)
		assert.False(t, someInt32.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt32 := option.NoneInt32()
		assert.True(t, emptyInt32.IsNil())
	})
}

func TestInt32_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt32 := option.SomeInt32(12)
		val, ok := someInt32.Get()
		require.True(t, ok)
		assert.EqualValues(t, 12, val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt32 := option.NoneInt32()
		_, ok := emptyInt32.Get()
		require.False(t, ok)
	})
}

func TestInt32_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt32 := option.SomeInt32(12)
		assert.EqualValues(t, 12, someInt32.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt32 := option.NoneInt32()
		assert.Panics(t, func() {
			emptyInt32.MustGet()
		})
	})
}

func TestInt32_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt32 := option.SomeInt32(12)
		assert.EqualValues(t, 12, someInt32.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt32 := option.NoneInt32()
		assert.NotPanics(t, func() {
			emptyInt32.Unwrap()
		})
	})
}

func TestInt32_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt32 := option.SomeInt32(12)
		assert.EqualValues(t, 12, someInt32.UnwrapOr(13))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt32 := option.NoneInt32()
		assert.EqualValues(t, 13, emptyInt32.UnwrapOr(13))
	})
}

func TestInt32_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt32 := option.SomeInt32(12)
		assert.EqualValues(t, 12, someInt32.UnwrapOrElse(func() int32 {
			return 13
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt32 := option.NoneInt32()
		assert.EqualValues(t, 13, emptyInt32.UnwrapOrElse(func() int32 {
			return 13
		}))
	})
}

func TestInt32_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someInt32 := option.SomeInt32(12)
		err := someInt32.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Int32
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, 12, unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyInt32 := option.NoneInt32()
		err := emptyInt32.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Int32
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}
