// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option

import (
	"bytes"
	"encoding/json"

	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"
)

// Int32 represents an optional value of type int32.
// It can either hold a valid int32 (IsSome == true) or be empty (IsZero == true).
type Int32 struct {
	value  int32
	exists bool
}

var _ commonInterface[int32] = (*Int32)(nil)

// SomeInt32 creates an optional Int32 with the given int32 value.
// The returned Int32 will have IsSome() == true and IsZero() == false.
func SomeInt32(value int32) Int32 {
	return Int32{
		value:  value,
		exists: true,
	}
}

// NoneInt32 creates an empty optional Int32 value.
// The returned Int32 will have IsSome() == false and IsZero() == true.
func NoneInt32() Int32 {
	return Int32{
		exists: false,
		value:  zero[int32](),
	}
}

// IsSome returns true if the Int32 contains a value.
// This indicates the value is explicitly set (not None).
func (o Int32) IsSome() bool {
	return o.exists
}

// IsZero returns true if the Int32 does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o Int32) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o Int32) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of int32, false).
//
// Recommended usage:
//
//	if value, ok := o.Get(); ok {
//	    // use value
//	}
func (o Int32) Get() (int32, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o Int32) MustGet() int32 {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for int32.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o Int32) Unwrap() int32 {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
func (o Int32) UnwrapOr(defaultValue int32) int32 {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
func (o Int32) UnwrapOrElse(defaultValue func() int32) int32 {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

// EncodeMsgpack encodes the Int32 value using MessagePack format.
// - If the value is present, it is encoded as int32.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o Int32) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return newEncodeError("Int32", encodeInt32(encoder, o.value))
	}

	return newEncodeError("Int32", encoder.EncodeNil())
}

// DecodeMsgpack decodes a Int32 value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneInt32)
//   - int32: interpreted as a present value (SomeInt32)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on int32: exists = true, value = decoded value
func (o *Int32) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return newDecodeError("Int32", err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return newDecodeError("Int32", decoder.Skip())
	case checkNumber(code):
		o.value, err = decodeInt32(decoder)
		if err != nil {
			return newDecodeError("Int32", err)
		}
		o.exists = true

		return err
	default:
		return newDecodeWithCodeError("Int32", code)
	}
}

// MarshalJSON implements the json.Marshaler interface.
//   - If the value is present, it is encoded exactly as json.Marshal encodes
//     the int32 value itself.
//   - If the value is absent (None), it is encoded as JSON null.
//
// A struct field of type Int32 with the "omitzero" JSON tag option is
// omitted when the value is absent, since IsZero reports absence.
// The "omitempty" option has no effect on it.
func (o Int32) MarshalJSON() ([]byte, error) {
	if !o.exists {
		return []byte("null"), nil
	}

	return json.Marshal(&o.value)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
//   - JSON null is decoded as no value (NoneInt32).
//   - Any other JSON value is decoded as int32 and stored as a present value.
//
// An error of decoding int32 is returned unchanged, and the receiver
// is left intact.
func (o *Int32) UnmarshalJSON(data []byte) error {
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		*o = NoneInt32()

		return nil
	}

	var value int32

	err := json.Unmarshal(data, &value)
	if err != nil {
		return err
	}

	*o = SomeInt32(value)

	return nil
}

// MarshalYAML implements the Marshaler interface of gopkg.in/yaml.v3
// (and yaml.v2) without depending on it.
//   - If the value is present, it returns a pointer to it, so the value is
//     encoded exactly as the YAML encoder encodes int32 itself.
//   - If the value is absent (None), it returns nil, which is encoded as null.
//
// A struct field of type Int32 with the "omitempty" YAML tag option is
// omitted when the value is absent, since the encoder consults IsZero.
func (o Int32) MarshalYAML() (any, error) {
	if !o.exists {
		return nil, nil
	}

	return &o.value, nil
}

// UnmarshalYAML implements the obsolete Unmarshaler interface of
// gopkg.in/yaml.v3 (the only one of yaml.v2) without depending on it.
//   - A null value is decoded as no value (NoneInt32).
//   - Any other value is decoded as int32 and stored as a present value.
//
// gopkg.in/yaml.v3 never calls this method for a null node (null, ~ or an
// empty value): it leaves the receiver unchanged. Decoding null into a zero
// Int32 therefore yields None, but decoding it into a present value
// keeps that value.
//
// An error of decoding int32 is returned unchanged, and the receiver
// is left intact.
func (o *Int32) UnmarshalYAML(unmarshal func(any) error) error {
	var value *int32

	err := unmarshal(&value)
	if err != nil {
		return err
	}

	if value == nil {
		*o = NoneInt32()

		return nil
	}

	*o = SomeInt32(*value)

	return nil
}
