// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option

import (
	"bytes"
	"encoding/json"

	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"
)

// Int64 represents an optional value of type int64.
// It can either hold a valid int64 (IsSome == true) or be empty (IsZero == true).
type Int64 struct {
	value  int64
	exists bool
}

var _ commonInterface[int64] = (*Int64)(nil)

// SomeInt64 creates an optional Int64 with the given int64 value.
// The returned Int64 will have IsSome() == true and IsZero() == false.
func SomeInt64(value int64) Int64 {
	return Int64{
		value:  value,
		exists: true,
	}
}

// NoneInt64 creates an empty optional Int64 value.
// The returned Int64 will have IsSome() == false and IsZero() == true.
func NoneInt64() Int64 {
	return Int64{
		exists: false,
		value:  zero[int64](),
	}
}

// IsSome returns true if the Int64 contains a value.
// This indicates the value is explicitly set (not None).
func (o Int64) IsSome() bool {
	return o.exists
}

// IsZero returns true if the Int64 does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o Int64) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o Int64) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of int64, false).
//
// Recommended usage:
//
//	if value, ok := o.Get(); ok {
//	    // use value
//	}
func (o Int64) Get() (int64, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o Int64) MustGet() int64 {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for int64.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o Int64) Unwrap() int64 {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
func (o Int64) UnwrapOr(defaultValue int64) int64 {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
func (o Int64) UnwrapOrElse(defaultValue func() int64) int64 {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

// EncodeMsgpack encodes the Int64 value using MessagePack format.
// - If the value is present, it is encoded as int64.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o Int64) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return newEncodeError("Int64", encodeInt64(encoder, o.value))
	}

	return newEncodeError("Int64", encoder.EncodeNil())
}

// DecodeMsgpack decodes a Int64 value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneInt64)
//   - int64: interpreted as a present value (SomeInt64)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on int64: exists = true, value = decoded value
func (o *Int64) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return newDecodeError("Int64", err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return newDecodeError("Int64", decoder.Skip())
	case checkNumber(code):
		o.value, err = decodeInt64(decoder)
		if err != nil {
			return newDecodeError("Int64", err)
		}
		o.exists = true

		return err
	default:
		return newDecodeWithCodeError("Int64", code)
	}
}

// MarshalJSON implements the json.Marshaler interface.
//   - If the value is present, it is encoded exactly as json.Marshal encodes
//     the int64 value itself.
//   - If the value is absent (None), it is encoded as JSON null.
//
// A struct field of type Int64 with the "omitzero" JSON tag option is
// omitted when the value is absent, since IsZero reports absence.
// The "omitempty" option has no effect on it.
func (o Int64) MarshalJSON() ([]byte, error) {
	if !o.exists {
		return []byte("null"), nil
	}

	return json.Marshal(&o.value)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
//   - JSON null is decoded as no value (NoneInt64).
//   - Any other JSON value is decoded as int64 and stored as a present value.
//
// An error of decoding int64 is returned unchanged, and the receiver
// is left intact.
func (o *Int64) UnmarshalJSON(data []byte) error {
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		*o = NoneInt64()

		return nil
	}

	var value int64

	err := json.Unmarshal(data, &value)
	if err != nil {
		return err
	}

	*o = SomeInt64(value)

	return nil
}

// MarshalYAML implements the Marshaler interface of gopkg.in/yaml.v3
// (and yaml.v2) without depending on it.
//   - If the value is present, it returns a pointer to it, so the value is
//     encoded exactly as the YAML encoder encodes int64 itself.
//   - If the value is absent (None), it returns nil, which is encoded as null.
//
// A struct field of type Int64 with the "omitempty" YAML tag option is
// omitted when the value is absent, since the encoder consults IsZero.
func (o Int64) MarshalYAML() (any, error) {
	if !o.exists {
		return nil, nil
	}

	return &o.value, nil
}

// UnmarshalYAML implements the obsolete Unmarshaler interface of
// gopkg.in/yaml.v3 (the only one of yaml.v2) without depending on it.
//   - A null value is decoded as no value (NoneInt64).
//   - Any other value is decoded as int64 and stored as a present value.
//
// gopkg.in/yaml.v3 never calls this method for a null node (null, ~ or an
// empty value): it leaves the receiver unchanged. Decoding null into a zero
// Int64 therefore yields None, but decoding it into a present value
// keeps that value.
//
// An error of decoding int64 is returned unchanged, and the receiver
// is left intact.
func (o *Int64) UnmarshalYAML(unmarshal func(any) error) error {
	var value *int64

	err := unmarshal(&value)
	if err != nil {
		return err
	}

	if value == nil {
		*o = NoneInt64()

		return nil
	}

	*o = SomeInt64(*value)

	return nil
}
