// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"
	"gopkg.in/yaml.v3"

	"github.com/tarantool/go-option"
)

func TestInt8_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt8 := option.SomeInt8(12)
		assert.True(t, someInt8.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt8 := option.NoneInt8()
		assert.False(t, emptyInt8.IsSome())
	})
}

func TestInt8_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt8 := option.SomeInt8(12)
		assert.False(t, someInt8.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt8 := option.NoneInt8()
		assert.True(t, emptyInt8.IsZero())
	})
}

func TestInt8_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt8 := option.SomeInt8(12)
		assert.False(t, someInt8.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt8 := option.NoneInt8()
		assert.True(t, emptyInt8.IsNil())
	})
}

func TestInt8_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt8 := option.SomeInt8(12)
		val, ok := someInt8.Get()
		require.True(t, ok)
		assert.EqualValues(t, 12, val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt8 := option.NoneInt8()
		_, ok := emptyInt8.Get()
		require.False(t, ok)
	})
}

func TestInt8_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt8 := option.SomeInt8(12)
		assert.EqualValues(t, 12, someInt8.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt8 := option.NoneInt8()
		assert.Panics(t, func() {
			emptyInt8.MustGet()
		})
	})
}

func TestInt8_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt8 := option.SomeInt8(12)
		assert.EqualValues(t, 12, someInt8.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt8 := option.NoneInt8()
		assert.NotPanics(t, func() {
			emptyInt8.Unwrap()
		})
	})
}

func TestInt8_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt8 := option.SomeInt8(12)
		assert.EqualValues(t, 12, someInt8.UnwrapOr(13))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt8 := option.NoneInt8()
		assert.EqualValues(t, 13, emptyInt8.UnwrapOr(13))
	})
}

func TestInt8_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt8 := option.SomeInt8(12)
		assert.EqualValues(t, 12, someInt8.UnwrapOrElse(func() int8 {
			return 13
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt8 := option.NoneInt8()
		assert.EqualValues(t, 13, emptyInt8.UnwrapOrElse(func() int8 {
			return 13
		}))
	})
}

func TestInt8_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someInt8 := option.SomeInt8(12)
		err := someInt8.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Int8
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, 12, unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyInt8 := option.NoneInt8()
		err := emptyInt8.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Int8
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}

func TestInt8_MarshalJSON(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.SomeInt8(12))
		require.NoError(t, err)
		assert.Equal(t, `12`, string(data))
	})

	t.Run("some_as_inner_0", func(t *testing.T) {
		t.Parallel()

		expected, err := json.Marshal(int8(12))
		require.NoError(t, err)

		data, err := json.Marshal(option.SomeInt8(12))
		require.NoError(t, err)
		assert.Equal(t, string(expected), string(data))
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.SomeInt8(0))
		require.NoError(t, err)
		assert.Equal(t, `0`, string(data))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.NoneInt8())
		require.NoError(t, err)
		assert.Equal(t, "null", string(data))
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some option.Int8 `json:"some"`
			None option.Int8 `json:"none"`
		}

		data, err := json.Marshal(wrapper{
			Some: option.SomeInt8(12),
			None: option.NoneInt8(),
		})
		require.NoError(t, err)
		assert.Equal(t, `{"some":12,"none":null}`, string(data))
	})

	t.Run("omitzero", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Value option.Int8 `json:"value,omitzero"`
		}

		data, err := json.Marshal(wrapper{Value: option.NoneInt8()})
		require.NoError(t, err)
		assert.Equal(t, "{}", string(data))

		data, err = json.Marshal(wrapper{Value: option.SomeInt8(0)})
		require.NoError(t, err)
		assert.Equal(t, `{"value":0}`, string(data))
	})
}

func TestInt8_UnmarshalJSON(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var opt option.Int8
		require.NoError(t, json.Unmarshal([]byte(`12`), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("roundtrip_0", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.SomeInt8(12))
		require.NoError(t, err)

		var opt option.Int8
		require.NoError(t, json.Unmarshal(data, &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		var opt option.Int8
		require.NoError(t, json.Unmarshal([]byte(`0`), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 0, opt.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeInt8(12)
		require.NoError(t, json.Unmarshal([]byte("null"), &opt))
		assert.False(t, opt.IsSome())
		assert.Zero(t, opt.Unwrap())
	})

	t.Run("none_with_spaces", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeInt8(12)
		require.NoError(t, opt.UnmarshalJSON([]byte(" null\n")))
		assert.False(t, opt.IsSome())
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some   option.Int8 `json:"some"`
			None   option.Int8 `json:"none"`
			Absent option.Int8 `json:"absent"`
		}

		var out wrapper
		err := json.Unmarshal([]byte(`{"some":12,"none":null}`), &out)
		require.NoError(t, err)
		require.True(t, out.Some.IsSome())
		assert.EqualValues(t, 12, out.Some.Unwrap())
		assert.False(t, out.None.IsSome())
		assert.False(t, out.Absent.IsSome())
	})

	t.Run("invalid", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeInt8(12)
		err := opt.UnmarshalJSON([]byte("{"))

		var syntaxErr *json.SyntaxError
		require.ErrorAs(t, err, &syntaxErr)
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})
}

func TestInt8_MarshalYAML(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.SomeInt8(12))
		require.NoError(t, err)
		assert.Equal(t, "12\n", string(data))
	})

	t.Run("some_as_inner_0", func(t *testing.T) {
		t.Parallel()

		expected, err := yaml.Marshal(int8(12))
		require.NoError(t, err)

		data, err := yaml.Marshal(option.SomeInt8(12))
		require.NoError(t, err)
		assert.Equal(t, string(expected), string(data))
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.SomeInt8(0))
		require.NoError(t, err)
		assert.Equal(t, "0\n", string(data))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.NoneInt8())
		require.NoError(t, err)
		assert.Equal(t, "null\n", string(data))
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some    option.Int8 `yaml:"some"`
			None    option.Int8 `yaml:"none"`
			Omitted option.Int8 `yaml:"omitted,omitempty"`
			Zero    option.Int8 `yaml:"zero,omitempty"`
		}

		data, err := yaml.Marshal(wrapper{
			Some:    option.SomeInt8(12),
			None:    option.NoneInt8(),
			Omitted: option.NoneInt8(),
			Zero:    option.SomeInt8(0),
		})
		require.NoError(t, err)

		var fields map[string]any
		require.NoError(t, yaml.Unmarshal(data, &fields))
		assert.Contains(t, fields, "some")
		assert.NotNil(t, fields["some"])
		assert.Contains(t, fields, "none")
		assert.Nil(t, fields["none"])
		assert.NotContains(t, fields, "omitted")
		assert.Contains(t, fields, "zero")
		assert.NotNil(t, fields["zero"])
	})
}

func TestInt8_UnmarshalYAML(t *testing.T) {
	t.Parallel()

	t.Run("roundtrip_0", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.SomeInt8(12))
		require.NoError(t, err)

		var opt option.Int8
		require.NoError(t, yaml.Unmarshal(data, &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		var opt option.Int8
		require.NoError(t, yaml.Unmarshal([]byte("0\n"), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 0, opt.Unwrap())
	})

	t.Run("none_roundtrip", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.NoneInt8())
		require.NoError(t, err)

		var opt option.Int8
		require.NoError(t, yaml.Unmarshal(data, &opt))
		assert.False(t, opt.IsSome())
	})

	t.Run("null_node_keeps_present_value", func(t *testing.T) {
		t.Parallel()

		// gopkg.in/yaml.v3 does not call UnmarshalYAML for a null node.
		opt := option.SomeInt8(12)
		require.NoError(t, yaml.Unmarshal([]byte("null"), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("null_by_direct_call", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeInt8(12)
		err := opt.UnmarshalYAML(func(v any) error {
			return yaml.Unmarshal([]byte("null"), v)
		})
		require.NoError(t, err)
		assert.False(t, opt.IsSome())
		assert.Zero(t, opt.Unwrap())
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some   option.Int8 `yaml:"some"`
			Null   option.Int8 `yaml:"nulled"`
			Tilde  option.Int8 `yaml:"tilde"`
			Empty  option.Int8 `yaml:"empty"`
			Absent option.Int8 `yaml:"absent"`
		}

		some, err := yaml.Marshal(map[string]any{"some": option.SomeInt8(12)})
		require.NoError(t, err)

		var out wrapper
		require.NoError(t, yaml.Unmarshal(append(some, []byte("nulled: null\ntilde: ~\nempty:\n")...), &out))
		require.True(t, out.Some.IsSome())
		assert.EqualValues(t, 12, out.Some.Unwrap())
		assert.False(t, out.Null.IsSome())
		assert.False(t, out.Tilde.IsSome())
		assert.False(t, out.Empty.IsSome())
		assert.False(t, out.Absent.IsSome())
	})

	t.Run("error", func(t *testing.T) {
		t.Parallel()

		errUnmarshal := errors.New("unmarshal failed")

		opt := option.SomeInt8(12)
		err := opt.UnmarshalYAML(func(any) error {
			return errUnmarshal
		})
		require.ErrorIs(t, err, errUnmarshal)
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})
}

func ExampleInt8_MarshalJSON() {
	for _, opt := range []option.Int8{option.SomeInt8(12), option.NoneInt8()} {
		data, err := json.Marshal(opt)
		if err != nil {
			fmt.Println("error:", err)

			return
		}

		fmt.Println(string(data))
	}
	// Output:
	// 12
	// null
}

func ExampleSomeInt8() {
	opt := option.SomeInt8(12)
	if opt.IsSome() {
		fmt.Println(opt.Unwrap())
	}
	// Output: 12
}

func ExampleNoneInt8() {
	opt := option.NoneInt8()
	if opt.IsZero() {
		fmt.Println("value is absent")
	}
	// Output: value is absent
}

func ExampleInt8_IsSome() {
	some := option.SomeInt8(12)
	none := option.NoneInt8()
	fmt.Println(some.IsSome())
	fmt.Println(none.IsSome())
	// Output:
	// true
	// false
}

func ExampleInt8_IsZero() {
	some := option.SomeInt8(12)
	none := option.NoneInt8()
	fmt.Println(some.IsZero())
	fmt.Println(none.IsZero())
	// Output:
	// false
	// true
}

func ExampleInt8_IsNil() {
	some := option.SomeInt8(12)
	none := option.NoneInt8()
	fmt.Println(some.IsNil() == some.IsZero())
	fmt.Println(none.IsNil() == none.IsZero())
	// Output:
	// true
	// true
}

func ExampleInt8_Get() {
	some := option.SomeInt8(12)
	none := option.NoneInt8()
	val, ok := some.Get()
	fmt.Println(val, ok)
	val, ok = none.Get()
	fmt.Println(val, ok)
	// Output:
	// 12 true
	// 0 false
}

func ExampleInt8_MustGet() {
	some := option.SomeInt8(12)
	fmt.Println(some.MustGet())
	// Output: 12
}

func ExampleInt8_MustGet_panic() {
	none := option.NoneInt8()
	eof := false
	defer func() {
		if !eof {
			fmt.Println("panic!", recover())
		}
	}()
	fmt.Println(none.MustGet())
	eof = true
	// Output: panic! optional value is not set
}

func ExampleInt8_Unwrap() {
	some := option.SomeInt8(12)
	none := option.NoneInt8()
	fmt.Println(some.Unwrap())
	fmt.Println(none.Unwrap())
	// Output:
	// 12
	// 0
}

func ExampleInt8_UnwrapOr() {
	some := option.SomeInt8(12)
	none := option.NoneInt8()
	fmt.Println(some.UnwrapOr(13))
	fmt.Println(none.UnwrapOr(13))
	// Output:
	// 12
	// 13
}

func ExampleInt8_UnwrapOrElse() {
	some := option.SomeInt8(12)
	none := option.NoneInt8()
	fmt.Println(some.UnwrapOrElse(func() int8 {
		return 13
	}))
	fmt.Println(none.UnwrapOrElse(func() int8 {
		return 13
	}))
	// Output:
	// 12
	// 13
}
