// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"

	"github.com/tarantool/go-option"
)

func TestInt_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.True(t, someInt.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.False(t, emptyInt.IsSome())
	})
}

func TestInt_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.False(t, someInt.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.True(t, emptyInt.IsZero())
	})
}

func TestInt_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.False(t, someInt.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.True(t, emptyInt.IsNil())
	})
}

func TestInt_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		val, ok := someInt.Get()
		require.True(t, ok)
		assert.EqualValues(t, 12, val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		_, ok := emptyInt.Get()
		require.False(t, ok)
	})
}

func TestInt_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.EqualValues(t, 12, someInt.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.Panics(t, func() {
			emptyInt.MustGet()
		})
	})
}

func TestInt_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.EqualValues(t, 12, someInt.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.NotPanics(t, func() {
			emptyInt.Unwrap()
		})
	})
}

func TestInt_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.EqualValues(t, 12, someInt.UnwrapOr(13))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.EqualValues(t, 13, emptyInt.UnwrapOr(13))
	})
}

func TestInt_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.EqualValues(t, 12, someInt.UnwrapOrElse(func() int {
			return 13
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.EqualValues(t, 13, emptyInt.UnwrapOrElse(func() int {
			return 13
		}))
	})
}

func TestInt_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someInt := option.SomeInt(12)
		err := someInt.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Int
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, 12, unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyInt := option.NoneInt()
		err := emptyInt.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Int
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}
