// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"

	"github.com/tarantool/go-option"
)

func TestInt_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.True(t, someInt.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.False(t, emptyInt.IsSome())
	})
}

func TestInt_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.False(t, someInt.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.True(t, emptyInt.IsZero())
	})
}

func TestInt_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.False(t, someInt.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.True(t, emptyInt.IsNil())
	})
}

func TestInt_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		val, ok := someInt.Get()
		require.True(t, ok)
		assert.EqualValues(t, 12, val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		_, ok := emptyInt.Get()
		require.False(t, ok)
	})
}

func TestInt_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.EqualValues(t, 12, someInt.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.Panics(t, func() {
			emptyInt.MustGet()
		})
	})
}

func TestInt_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.EqualValues(t, 12, someInt.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.NotPanics(t, func() {
			emptyInt.Unwrap()
		})
	})
}

func TestInt_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.EqualValues(t, 12, someInt.UnwrapOr(13))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.EqualValues(t, 13, emptyInt.UnwrapOr(13))
	})
}

func TestInt_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.EqualValues(t, 12, someInt.UnwrapOrElse(func() int {
			return 13
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.EqualValues(t, 13, emptyInt.UnwrapOrElse(func() int {
			return 13
		}))
	})
}

func TestInt_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someInt := option.SomeInt(12)
		err := someInt.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Int
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, 12, unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyInt := option.NoneInt()
		err := emptyInt.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Int
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}

func ExampleSomeInt() {
	opt := option.SomeInt(12)
	if opt.IsSome() {
		fmt.Println(opt.Unwrap())
	}
	// Output: 12
}

func ExampleNoneInt() {
	opt := option.NoneInt()
	if opt.IsZero() {
		fmt.Println("value is absent")
	}
	// Output: value is absent
}

func ExampleInt_IsSome() {
	some := option.SomeInt(12)
	none := option.NoneInt()
	fmt.Println(some.IsSome())
	fmt.Println(none.IsSome())
	// Output:
	// true
	// false
}

func ExampleInt_IsZero() {
	some := option.SomeInt(12)
	none := option.NoneInt()
	fmt.Println(some.IsZero())
	fmt.Println(none.IsZero())
	// Output:
	// false
	// true
}

func ExampleInt_IsNil() {
	some := option.SomeInt(12)
	none := option.NoneInt()
	fmt.Println(some.IsNil() == some.IsZero())
	fmt.Println(none.IsNil() == none.IsZero())
	// Output:
	// true
	// true
}

func ExampleInt_Get() {
	some := option.SomeInt(12)
	none := option.NoneInt()
	val, ok := some.Get()
	fmt.Println(val, ok)
	val, ok = none.Get()
	fmt.Println(val, ok)
	// Output:
	// 12 true
	// 0 false
}

func ExampleInt_MustGet() {
	some := option.SomeInt(12)
	fmt.Println(some.MustGet())
	// Output: 12
}

func ExampleInt_MustGet_panic() {
	none := option.NoneInt()
	eof := false
	defer func() {
		if !eof {
			fmt.Println("panic!", recover())
		}
	}()
	fmt.Println(none.MustGet())
	eof = true
	// Output: panic! optional value is not set
}

func ExampleInt_Unwrap() {
	some := option.SomeInt(12)
	none := option.NoneInt()
	fmt.Println(some.Unwrap())
	fmt.Println(none.Unwrap())
	// Output:
	// 12
	// 0
}

func ExampleInt_UnwrapOr() {
	some := option.SomeInt(12)
	none := option.NoneInt()
	fmt.Println(some.UnwrapOr(13))
	fmt.Println(none.UnwrapOr(13))
	// Output:
	// 12
	// 13
}

func ExampleInt_UnwrapOrElse() {
	some := option.SomeInt(12)
	none := option.NoneInt()
	fmt.Println(some.UnwrapOrElse(func() int {
		return 13
	}))
	fmt.Println(none.UnwrapOrElse(func() int {
		return 13
	}))
	// Output:
	// 12
	// 13
}
