// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"
	"gopkg.in/yaml.v3"

	"github.com/tarantool/go-option"
)

func TestInt_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.True(t, someInt.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.False(t, emptyInt.IsSome())
	})
}

func TestInt_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.False(t, someInt.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.True(t, emptyInt.IsZero())
	})
}

func TestInt_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.False(t, someInt.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.True(t, emptyInt.IsNil())
	})
}

func TestInt_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		val, ok := someInt.Get()
		require.True(t, ok)
		assert.EqualValues(t, 12, val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		_, ok := emptyInt.Get()
		require.False(t, ok)
	})
}

func TestInt_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.EqualValues(t, 12, someInt.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.Panics(t, func() {
			emptyInt.MustGet()
		})
	})
}

func TestInt_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.EqualValues(t, 12, someInt.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.NotPanics(t, func() {
			emptyInt.Unwrap()
		})
	})
}

func TestInt_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.EqualValues(t, 12, someInt.UnwrapOr(13))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.EqualValues(t, 13, emptyInt.UnwrapOr(13))
	})
}

func TestInt_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someInt := option.SomeInt(12)
		assert.EqualValues(t, 12, someInt.UnwrapOrElse(func() int {
			return 13
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyInt := option.NoneInt()
		assert.EqualValues(t, 13, emptyInt.UnwrapOrElse(func() int {
			return 13
		}))
	})
}

func TestInt_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someInt := option.SomeInt(12)
		err := someInt.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Int
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, 12, unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyInt := option.NoneInt()
		err := emptyInt.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Int
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}

func TestInt_MarshalJSON(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.SomeInt(12))
		require.NoError(t, err)
		assert.Equal(t, `12`, string(data))
	})

	t.Run("some_as_inner_0", func(t *testing.T) {
		t.Parallel()

		expected, err := json.Marshal(int(12))
		require.NoError(t, err)

		data, err := json.Marshal(option.SomeInt(12))
		require.NoError(t, err)
		assert.Equal(t, string(expected), string(data))
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.SomeInt(0))
		require.NoError(t, err)
		assert.Equal(t, `0`, string(data))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.NoneInt())
		require.NoError(t, err)
		assert.Equal(t, "null", string(data))
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some option.Int `json:"some"`
			None option.Int `json:"none"`
		}

		data, err := json.Marshal(wrapper{
			Some: option.SomeInt(12),
			None: option.NoneInt(),
		})
		require.NoError(t, err)
		assert.Equal(t, `{"some":12,"none":null}`, string(data))
	})

	t.Run("omitzero", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Value option.Int `json:"value,omitzero"`
		}

		data, err := json.Marshal(wrapper{Value: option.NoneInt()})
		require.NoError(t, err)
		assert.Equal(t, "{}", string(data))

		data, err = json.Marshal(wrapper{Value: option.SomeInt(0)})
		require.NoError(t, err)
		assert.Equal(t, `{"value":0}`, string(data))
	})
}

func TestInt_UnmarshalJSON(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var opt option.Int
		require.NoError(t, json.Unmarshal([]byte(`12`), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("roundtrip_0", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.SomeInt(12))
		require.NoError(t, err)

		var opt option.Int
		require.NoError(t, json.Unmarshal(data, &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		var opt option.Int
		require.NoError(t, json.Unmarshal([]byte(`0`), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 0, opt.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeInt(12)
		require.NoError(t, json.Unmarshal([]byte("null"), &opt))
		assert.False(t, opt.IsSome())
		assert.Zero(t, opt.Unwrap())
	})

	t.Run("none_with_spaces", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeInt(12)
		require.NoError(t, opt.UnmarshalJSON([]byte(" null\n")))
		assert.False(t, opt.IsSome())
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some   option.Int `json:"some"`
			None   option.Int `json:"none"`
			Absent option.Int `json:"absent"`
		}

		var out wrapper
		err := json.Unmarshal([]byte(`{"some":12,"none":null}`), &out)
		require.NoError(t, err)
		require.True(t, out.Some.IsSome())
		assert.EqualValues(t, 12, out.Some.Unwrap())
		assert.False(t, out.None.IsSome())
		assert.False(t, out.Absent.IsSome())
	})

	t.Run("invalid", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeInt(12)
		err := opt.UnmarshalJSON([]byte("{"))

		var syntaxErr *json.SyntaxError
		require.ErrorAs(t, err, &syntaxErr)
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})
}

func TestInt_MarshalYAML(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.SomeInt(12))
		require.NoError(t, err)
		assert.Equal(t, "12\n", string(data))
	})

	t.Run("some_as_inner_0", func(t *testing.T) {
		t.Parallel()

		expected, err := yaml.Marshal(int(12))
		require.NoError(t, err)

		data, err := yaml.Marshal(option.SomeInt(12))
		require.NoError(t, err)
		assert.Equal(t, string(expected), string(data))
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.SomeInt(0))
		require.NoError(t, err)
		assert.Equal(t, "0\n", string(data))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.NoneInt())
		require.NoError(t, err)
		assert.Equal(t, "null\n", string(data))
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some    option.Int `yaml:"some"`
			None    option.Int `yaml:"none"`
			Omitted option.Int `yaml:"omitted,omitempty"`
			Zero    option.Int `yaml:"zero,omitempty"`
		}

		data, err := yaml.Marshal(wrapper{
			Some:    option.SomeInt(12),
			None:    option.NoneInt(),
			Omitted: option.NoneInt(),
			Zero:    option.SomeInt(0),
		})
		require.NoError(t, err)

		var fields map[string]any
		require.NoError(t, yaml.Unmarshal(data, &fields))
		assert.Contains(t, fields, "some")
		assert.NotNil(t, fields["some"])
		assert.Contains(t, fields, "none")
		assert.Nil(t, fields["none"])
		assert.NotContains(t, fields, "omitted")
		assert.Contains(t, fields, "zero")
		assert.NotNil(t, fields["zero"])
	})
}

func TestInt_UnmarshalYAML(t *testing.T) {
	t.Parallel()

	t.Run("roundtrip_0", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.SomeInt(12))
		require.NoError(t, err)

		var opt option.Int
		require.NoError(t, yaml.Unmarshal(data, &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		var opt option.Int
		require.NoError(t, yaml.Unmarshal([]byte("0\n"), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 0, opt.Unwrap())
	})

	t.Run("none_roundtrip", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.NoneInt())
		require.NoError(t, err)

		var opt option.Int
		require.NoError(t, yaml.Unmarshal(data, &opt))
		assert.False(t, opt.IsSome())
	})

	t.Run("null_node_keeps_present_value", func(t *testing.T) {
		t.Parallel()

		// gopkg.in/yaml.v3 does not call UnmarshalYAML for a null node.
		opt := option.SomeInt(12)
		require.NoError(t, yaml.Unmarshal([]byte("null"), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("null_by_direct_call", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeInt(12)
		err := opt.UnmarshalYAML(func(v any) error {
			return yaml.Unmarshal([]byte("null"), v)
		})
		require.NoError(t, err)
		assert.False(t, opt.IsSome())
		assert.Zero(t, opt.Unwrap())
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some   option.Int `yaml:"some"`
			Null   option.Int `yaml:"nulled"`
			Tilde  option.Int `yaml:"tilde"`
			Empty  option.Int `yaml:"empty"`
			Absent option.Int `yaml:"absent"`
		}

		some, err := yaml.Marshal(map[string]any{"some": option.SomeInt(12)})
		require.NoError(t, err)

		var out wrapper
		require.NoError(t, yaml.Unmarshal(append(some, []byte("nulled: null\ntilde: ~\nempty:\n")...), &out))
		require.True(t, out.Some.IsSome())
		assert.EqualValues(t, 12, out.Some.Unwrap())
		assert.False(t, out.Null.IsSome())
		assert.False(t, out.Tilde.IsSome())
		assert.False(t, out.Empty.IsSome())
		assert.False(t, out.Absent.IsSome())
	})

	t.Run("error", func(t *testing.T) {
		t.Parallel()

		errUnmarshal := errors.New("unmarshal failed")

		opt := option.SomeInt(12)
		err := opt.UnmarshalYAML(func(any) error {
			return errUnmarshal
		})
		require.ErrorIs(t, err, errUnmarshal)
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})
}

func ExampleInt_MarshalJSON() {
	for _, opt := range []option.Int{option.SomeInt(12), option.NoneInt()} {
		data, err := json.Marshal(opt)
		if err != nil {
			fmt.Println("error:", err)

			return
		}

		fmt.Println(string(data))
	}
	// Output:
	// 12
	// null
}

func ExampleSomeInt() {
	opt := option.SomeInt(12)
	if opt.IsSome() {
		fmt.Println(opt.Unwrap())
	}
	// Output: 12
}

func ExampleNoneInt() {
	opt := option.NoneInt()
	if opt.IsZero() {
		fmt.Println("value is absent")
	}
	// Output: value is absent
}

func ExampleInt_IsSome() {
	some := option.SomeInt(12)
	none := option.NoneInt()
	fmt.Println(some.IsSome())
	fmt.Println(none.IsSome())
	// Output:
	// true
	// false
}

func ExampleInt_IsZero() {
	some := option.SomeInt(12)
	none := option.NoneInt()
	fmt.Println(some.IsZero())
	fmt.Println(none.IsZero())
	// Output:
	// false
	// true
}

func ExampleInt_IsNil() {
	some := option.SomeInt(12)
	none := option.NoneInt()
	fmt.Println(some.IsNil() == some.IsZero())
	fmt.Println(none.IsNil() == none.IsZero())
	// Output:
	// true
	// true
}

func ExampleInt_Get() {
	some := option.SomeInt(12)
	none := option.NoneInt()
	val, ok := some.Get()
	fmt.Println(val, ok)
	val, ok = none.Get()
	fmt.Println(val, ok)
	// Output:
	// 12 true
	// 0 false
}

func ExampleInt_MustGet() {
	some := option.SomeInt(12)
	fmt.Println(some.MustGet())
	// Output: 12
}

func ExampleInt_MustGet_panic() {
	none := option.NoneInt()
	eof := false
	defer func() {
		if !eof {
			fmt.Println("panic!", recover())
		}
	}()
	fmt.Println(none.MustGet())
	eof = true
	// Output: panic! optional value is not set
}

func ExampleInt_Unwrap() {
	some := option.SomeInt(12)
	none := option.NoneInt()
	fmt.Println(some.Unwrap())
	fmt.Println(none.Unwrap())
	// Output:
	// 12
	// 0
}

func ExampleInt_UnwrapOr() {
	some := option.SomeInt(12)
	none := option.NoneInt()
	fmt.Println(some.UnwrapOr(13))
	fmt.Println(none.UnwrapOr(13))
	// Output:
	// 12
	// 13
}

func ExampleInt_UnwrapOrElse() {
	some := option.SomeInt(12)
	none := option.NoneInt()
	fmt.Println(some.UnwrapOrElse(func() int {
		return 13
	}))
	fmt.Println(none.UnwrapOrElse(func() int {
		return 13
	}))
	// Output:
	// 12
	// 13
}
