// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option

import (
	"bytes"
	"encoding/json"

	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"
)

// Int represents an optional value of type int.
// It can either hold a valid int (IsSome == true) or be empty (IsZero == true).
type Int struct {
	value  int
	exists bool
}

var _ commonInterface[int] = (*Int)(nil)

// SomeInt creates an optional Int with the given int value.
// The returned Int will have IsSome() == true and IsZero() == false.
func SomeInt(value int) Int {
	return Int{
		value:  value,
		exists: true,
	}
}

// NoneInt creates an empty optional Int value.
// The returned Int will have IsSome() == false and IsZero() == true.
func NoneInt() Int {
	return Int{
		exists: false,
		value:  zero[int](),
	}
}

// IsSome returns true if the Int contains a value.
// This indicates the value is explicitly set (not None).
func (o Int) IsSome() bool {
	return o.exists
}

// IsZero returns true if the Int does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o Int) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o Int) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of int, false).
//
// Recommended usage:
//
//	if value, ok := o.Get(); ok {
//	    // use value
//	}
func (o Int) Get() (int, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o Int) MustGet() int {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for int.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o Int) Unwrap() int {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
func (o Int) UnwrapOr(defaultValue int) int {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
func (o Int) UnwrapOrElse(defaultValue func() int) int {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

// EncodeMsgpack encodes the Int value using MessagePack format.
// - If the value is present, it is encoded as int.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o Int) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return newEncodeError("Int", encodeInt(encoder, o.value))
	}

	return newEncodeError("Int", encoder.EncodeNil())
}

// DecodeMsgpack decodes a Int value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneInt)
//   - int: interpreted as a present value (SomeInt)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on int: exists = true, value = decoded value
func (o *Int) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return newDecodeError("Int", err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return newDecodeError("Int", decoder.Skip())
	case checkNumber(code):
		o.value, err = decodeInt(decoder)
		if err != nil {
			return newDecodeError("Int", err)
		}
		o.exists = true

		return err
	default:
		return newDecodeWithCodeError("Int", code)
	}
}

// MarshalJSON implements the json.Marshaler interface.
//   - If the value is present, it is encoded exactly as json.Marshal encodes
//     the int value itself.
//   - If the value is absent (None), it is encoded as JSON null.
//
// A struct field of type Int with the "omitzero" JSON tag option is
// omitted when the value is absent, since IsZero reports absence.
// The "omitempty" option has no effect on it.
func (o Int) MarshalJSON() ([]byte, error) {
	if !o.exists {
		return []byte("null"), nil
	}

	return json.Marshal(&o.value)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
//   - JSON null is decoded as no value (NoneInt).
//   - Any other JSON value is decoded as int and stored as a present value.
//
// An error of decoding int is returned unchanged, and the receiver
// is left intact.
func (o *Int) UnmarshalJSON(data []byte) error {
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		*o = NoneInt()

		return nil
	}

	var value int

	err := json.Unmarshal(data, &value)
	if err != nil {
		return err
	}

	*o = SomeInt(value)

	return nil
}

// MarshalYAML implements the Marshaler interface of gopkg.in/yaml.v3
// (and yaml.v2) without depending on it.
//   - If the value is present, it returns a pointer to it, so the value is
//     encoded exactly as the YAML encoder encodes int itself.
//   - If the value is absent (None), it returns nil, which is encoded as null.
//
// A struct field of type Int with the "omitempty" YAML tag option is
// omitted when the value is absent, since the encoder consults IsZero.
func (o Int) MarshalYAML() (any, error) {
	if !o.exists {
		return nil, nil
	}

	return &o.value, nil
}

// UnmarshalYAML implements the obsolete Unmarshaler interface of
// gopkg.in/yaml.v3 (the only one of yaml.v2) without depending on it.
//   - A null value is decoded as no value (NoneInt).
//   - Any other value is decoded as int and stored as a present value.
//
// gopkg.in/yaml.v3 never calls this method for a null node (null, ~ or an
// empty value): it leaves the receiver unchanged. Decoding null into a zero
// Int therefore yields None, but decoding it into a present value
// keeps that value.
//
// An error of decoding int is returned unchanged, and the receiver
// is left intact.
func (o *Int) UnmarshalYAML(unmarshal func(any) error) error {
	var value *int

	err := unmarshal(&value)
	if err != nil {
		return err
	}

	if value == nil {
		*o = NoneInt()

		return nil
	}

	*o = SomeInt(*value)

	return nil
}
