// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"
	"gopkg.in/yaml.v3"

	"github.com/tarantool/go-option"
)

func TestString_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someString := option.SomeString("hello")
		assert.True(t, someString.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyString := option.NoneString()
		assert.False(t, emptyString.IsSome())
	})
}

func TestString_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someString := option.SomeString("hello")
		assert.False(t, someString.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyString := option.NoneString()
		assert.True(t, emptyString.IsZero())
	})
}

func TestString_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someString := option.SomeString("hello")
		assert.False(t, someString.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyString := option.NoneString()
		assert.True(t, emptyString.IsNil())
	})
}

func TestString_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someString := option.SomeString("hello")
		val, ok := someString.Get()
		require.True(t, ok)
		assert.EqualValues(t, "hello", val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyString := option.NoneString()
		_, ok := emptyString.Get()
		require.False(t, ok)
	})
}

func TestString_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someString := option.SomeString("hello")
		assert.EqualValues(t, "hello", someString.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyString := option.NoneString()
		assert.Panics(t, func() {
			emptyString.MustGet()
		})
	})
}

func TestString_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someString := option.SomeString("hello")
		assert.EqualValues(t, "hello", someString.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyString := option.NoneString()
		assert.NotPanics(t, func() {
			emptyString.Unwrap()
		})
	})
}

func TestString_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someString := option.SomeString("hello")
		assert.EqualValues(t, "hello", someString.UnwrapOr("bye"))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyString := option.NoneString()
		assert.EqualValues(t, "bye", emptyString.UnwrapOr("bye"))
	})
}

func TestString_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someString := option.SomeString("hello")
		assert.EqualValues(t, "hello", someString.UnwrapOrElse(func() string {
			return "bye"
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyString := option.NoneString()
		assert.EqualValues(t, "bye", emptyString.UnwrapOrElse(func() string {
			return "bye"
		}))
	})
}

func TestString_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someString := option.SomeString("hello")
		err := someString.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.String
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, "hello", unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyString := option.NoneString()
		err := emptyString.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.String
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}

func TestString_MarshalJSON(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.SomeString("hello"))
		require.NoError(t, err)
		assert.Equal(t, `"hello"`, string(data))
	})

	t.Run("some_as_inner_0", func(t *testing.T) {
		t.Parallel()

		expected, err := json.Marshal(string("hello"))
		require.NoError(t, err)

		data, err := json.Marshal(option.SomeString("hello"))
		require.NoError(t, err)
		assert.Equal(t, string(expected), string(data))
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.SomeString(""))
		require.NoError(t, err)
		assert.Equal(t, `""`, string(data))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.NoneString())
		require.NoError(t, err)
		assert.Equal(t, "null", string(data))
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some option.String `json:"some"`
			None option.String `json:"none"`
		}

		data, err := json.Marshal(wrapper{
			Some: option.SomeString("hello"),
			None: option.NoneString(),
		})
		require.NoError(t, err)
		assert.Equal(t, `{"some":"hello","none":null}`, string(data))
	})

	t.Run("omitzero", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Value option.String `json:"value,omitzero"`
		}

		data, err := json.Marshal(wrapper{Value: option.NoneString()})
		require.NoError(t, err)
		assert.Equal(t, "{}", string(data))

		data, err = json.Marshal(wrapper{Value: option.SomeString("")})
		require.NoError(t, err)
		assert.Equal(t, `{"value":""}`, string(data))
	})
}

func TestString_UnmarshalJSON(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var opt option.String
		require.NoError(t, json.Unmarshal([]byte(`"hello"`), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, "hello", opt.Unwrap())
	})

	t.Run("roundtrip_0", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.SomeString("hello"))
		require.NoError(t, err)

		var opt option.String
		require.NoError(t, json.Unmarshal(data, &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, "hello", opt.Unwrap())
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		var opt option.String
		require.NoError(t, json.Unmarshal([]byte(`""`), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, "", opt.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeString("hello")
		require.NoError(t, json.Unmarshal([]byte("null"), &opt))
		assert.False(t, opt.IsSome())
		assert.Zero(t, opt.Unwrap())
	})

	t.Run("none_with_spaces", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeString("hello")
		require.NoError(t, opt.UnmarshalJSON([]byte(" null\n")))
		assert.False(t, opt.IsSome())
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some   option.String `json:"some"`
			None   option.String `json:"none"`
			Absent option.String `json:"absent"`
		}

		var out wrapper
		err := json.Unmarshal([]byte(`{"some":"hello","none":null}`), &out)
		require.NoError(t, err)
		require.True(t, out.Some.IsSome())
		assert.EqualValues(t, "hello", out.Some.Unwrap())
		assert.False(t, out.None.IsSome())
		assert.False(t, out.Absent.IsSome())
	})

	t.Run("invalid", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeString("hello")
		err := opt.UnmarshalJSON([]byte("{"))

		var syntaxErr *json.SyntaxError
		require.ErrorAs(t, err, &syntaxErr)
		require.True(t, opt.IsSome())
		assert.EqualValues(t, "hello", opt.Unwrap())
	})
}

func TestString_MarshalYAML(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.SomeString("hello"))
		require.NoError(t, err)
		assert.Equal(t, "hello\n", string(data))
	})

	t.Run("some_as_inner_0", func(t *testing.T) {
		t.Parallel()

		expected, err := yaml.Marshal(string("hello"))
		require.NoError(t, err)

		data, err := yaml.Marshal(option.SomeString("hello"))
		require.NoError(t, err)
		assert.Equal(t, string(expected), string(data))
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.SomeString(""))
		require.NoError(t, err)
		assert.Equal(t, "\"\"\n", string(data))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.NoneString())
		require.NoError(t, err)
		assert.Equal(t, "null\n", string(data))
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some    option.String `yaml:"some"`
			None    option.String `yaml:"none"`
			Omitted option.String `yaml:"omitted,omitempty"`
			Zero    option.String `yaml:"zero,omitempty"`
		}

		data, err := yaml.Marshal(wrapper{
			Some:    option.SomeString("hello"),
			None:    option.NoneString(),
			Omitted: option.NoneString(),
			Zero:    option.SomeString(""),
		})
		require.NoError(t, err)

		var fields map[string]any
		require.NoError(t, yaml.Unmarshal(data, &fields))
		assert.Contains(t, fields, "some")
		assert.NotNil(t, fields["some"])
		assert.Contains(t, fields, "none")
		assert.Nil(t, fields["none"])
		assert.NotContains(t, fields, "omitted")
		assert.Contains(t, fields, "zero")
		assert.NotNil(t, fields["zero"])
	})
}

func TestString_UnmarshalYAML(t *testing.T) {
	t.Parallel()

	t.Run("roundtrip_0", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.SomeString("hello"))
		require.NoError(t, err)

		var opt option.String
		require.NoError(t, yaml.Unmarshal(data, &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, "hello", opt.Unwrap())
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		var opt option.String
		require.NoError(t, yaml.Unmarshal([]byte("\"\"\n"), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, "", opt.Unwrap())
	})

	t.Run("none_roundtrip", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.NoneString())
		require.NoError(t, err)

		var opt option.String
		require.NoError(t, yaml.Unmarshal(data, &opt))
		assert.False(t, opt.IsSome())
	})

	t.Run("null_node_keeps_present_value", func(t *testing.T) {
		t.Parallel()

		// gopkg.in/yaml.v3 does not call UnmarshalYAML for a null node.
		opt := option.SomeString("hello")
		require.NoError(t, yaml.Unmarshal([]byte("null"), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, "hello", opt.Unwrap())
	})

	t.Run("null_by_direct_call", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeString("hello")
		err := opt.UnmarshalYAML(func(v any) error {
			return yaml.Unmarshal([]byte("null"), v)
		})
		require.NoError(t, err)
		assert.False(t, opt.IsSome())
		assert.Zero(t, opt.Unwrap())
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some   option.String `yaml:"some"`
			Null   option.String `yaml:"nulled"`
			Tilde  option.String `yaml:"tilde"`
			Empty  option.String `yaml:"empty"`
			Absent option.String `yaml:"absent"`
		}

		some, err := yaml.Marshal(map[string]any{"some": option.SomeString("hello")})
		require.NoError(t, err)

		var out wrapper
		require.NoError(t, yaml.Unmarshal(append(some, []byte("nulled: null\ntilde: ~\nempty:\n")...), &out))
		require.True(t, out.Some.IsSome())
		assert.EqualValues(t, "hello", out.Some.Unwrap())
		assert.False(t, out.Null.IsSome())
		assert.False(t, out.Tilde.IsSome())
		assert.False(t, out.Empty.IsSome())
		assert.False(t, out.Absent.IsSome())
	})

	t.Run("error", func(t *testing.T) {
		t.Parallel()

		errUnmarshal := errors.New("unmarshal failed")

		opt := option.SomeString("hello")
		err := opt.UnmarshalYAML(func(any) error {
			return errUnmarshal
		})
		require.ErrorIs(t, err, errUnmarshal)
		require.True(t, opt.IsSome())
		assert.EqualValues(t, "hello", opt.Unwrap())
	})
}

func ExampleString_MarshalJSON() {
	for _, opt := range []option.String{option.SomeString("hello"), option.NoneString()} {
		data, err := json.Marshal(opt)
		if err != nil {
			fmt.Println("error:", err)

			return
		}

		fmt.Println(string(data))
	}
	// Output:
	// "hello"
	// null
}

func ExampleSomeString() {
	opt := option.SomeString("hello")
	if opt.IsSome() {
		fmt.Println(opt.Unwrap())
	}
	// Output: hello
}

func ExampleNoneString() {
	opt := option.NoneString()
	if opt.IsZero() {
		fmt.Println("value is absent")
	}
	// Output: value is absent
}

func ExampleString_IsSome() {
	some := option.SomeString("hello")
	none := option.NoneString()
	fmt.Println(some.IsSome())
	fmt.Println(none.IsSome())
	// Output:
	// true
	// false
}

func ExampleString_IsZero() {
	some := option.SomeString("hello")
	none := option.NoneString()
	fmt.Println(some.IsZero())
	fmt.Println(none.IsZero())
	// Output:
	// false
	// true
}

func ExampleString_IsNil() {
	some := option.SomeString("hello")
	none := option.NoneString()
	fmt.Println(some.IsNil() == some.IsZero())
	fmt.Println(none.IsNil() == none.IsZero())
	// Output:
	// true
	// true
}

func ExampleString_Get() {
	some := option.SomeString("hello")
	none := option.NoneString()
	val, ok := some.Get()
	fmt.Println(val, ok)
	val, ok = none.Get()
	fmt.Println(val, ok)
	// Output:
	// hello true
	//  false
}

func ExampleString_MustGet() {
	some := option.SomeString("hello")
	fmt.Println(some.MustGet())
	// Output: hello
}

func ExampleString_MustGet_panic() {
	none := option.NoneString()
	eof := false
	defer func() {
		if !eof {
			fmt.Println("panic!", recover())
		}
	}()
	fmt.Println(none.MustGet())
	eof = true
	// Output: panic! optional value is not set
}

func ExampleString_Unwrap() {
	some := option.SomeString("hello")
	none := option.NoneString()
	fmt.Println(some.Unwrap())
	fmt.Println(none.Unwrap())
	// Output:
	// hello
	//
}

func ExampleString_UnwrapOr() {
	some := option.SomeString("hello")
	none := option.NoneString()
	fmt.Println(some.UnwrapOr("bye"))
	fmt.Println(none.UnwrapOr("bye"))
	// Output:
	// hello
	// bye
}

func ExampleString_UnwrapOrElse() {
	some := option.SomeString("hello")
	none := option.NoneString()
	fmt.Println(some.UnwrapOrElse(func() string {
		return "bye"
	}))
	fmt.Println(none.UnwrapOrElse(func() string {
		return "bye"
	}))
	// Output:
	// hello
	// bye
}
