// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option

import (
	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"
)

// String represents an optional value of type string.
// It can either hold a valid string (IsSome == true) or be empty (IsZero == true).
type String struct {
	value  string
	exists bool
}

var _ commonInterface[string] = (*String)(nil)

// SomeString creates an optional String with the given string value.
// The returned String will have IsSome() == true and IsZero() == false.
func SomeString(value string) String {
	return String{
		value:  value,
		exists: true,
	}
}

// NoneString creates an empty optional String value.
// The returned String will have IsSome() == false and IsZero() == true.
func NoneString() String {
	return String{
		exists: false,
		value:  zero[string](),
	}
}

// IsSome returns true if the String contains a value.
// This indicates the value is explicitly set (not None).
func (o String) IsSome() bool {
	return o.exists
}

// IsZero returns true if the String does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o String) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o String) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of string, false).
//
// Recommended usage:
//
//	if value, ok := o.Get(); ok {
//	    // use value
//	}
func (o String) Get() (string, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o String) MustGet() string {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for string.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o String) Unwrap() string {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
func (o String) UnwrapOr(defaultValue string) string {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
func (o String) UnwrapOrElse(defaultValue func() string) string {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

// EncodeMsgpack encodes the String value using MessagePack format.
// - If the value is present, it is encoded as string.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o String) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return newEncodeError("String", encodeString(encoder, o.value))
	}

	return newEncodeError("String", encoder.EncodeNil())
}

// DecodeMsgpack decodes a String value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneString)
//   - string: interpreted as a present value (SomeString)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on string: exists = true, value = decoded value
func (o *String) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return newDecodeError("String", err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return newDecodeError("String", decoder.Skip())
	case checkString(code):
		o.value, err = decodeString(decoder)
		if err != nil {
			return newDecodeError("String", err)
		}
		o.exists = true

		return err
	default:
		return newDecodeWithCodeError("String", code)
	}
}
