// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"

	"github.com/tarantool/go-option"
)

func TestUint8_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint8 := option.SomeUint8(12)
		assert.True(t, someUint8.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint8 := option.NoneUint8()
		assert.False(t, emptyUint8.IsSome())
	})
}

func TestUint8_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint8 := option.SomeUint8(12)
		assert.False(t, someUint8.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint8 := option.NoneUint8()
		assert.True(t, emptyUint8.IsZero())
	})
}

func TestUint8_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint8 := option.SomeUint8(12)
		assert.False(t, someUint8.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint8 := option.NoneUint8()
		assert.True(t, emptyUint8.IsNil())
	})
}

func TestUint8_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint8 := option.SomeUint8(12)
		val, ok := someUint8.Get()
		require.True(t, ok)
		assert.EqualValues(t, 12, val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint8 := option.NoneUint8()
		_, ok := emptyUint8.Get()
		require.False(t, ok)
	})
}

func TestUint8_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint8 := option.SomeUint8(12)
		assert.EqualValues(t, 12, someUint8.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint8 := option.NoneUint8()
		assert.Panics(t, func() {
			emptyUint8.MustGet()
		})
	})
}

func TestUint8_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint8 := option.SomeUint8(12)
		assert.EqualValues(t, 12, someUint8.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint8 := option.NoneUint8()
		assert.NotPanics(t, func() {
			emptyUint8.Unwrap()
		})
	})
}

func TestUint8_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint8 := option.SomeUint8(12)
		assert.EqualValues(t, 12, someUint8.UnwrapOr(13))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint8 := option.NoneUint8()
		assert.EqualValues(t, 13, emptyUint8.UnwrapOr(13))
	})
}

func TestUint8_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint8 := option.SomeUint8(12)
		assert.EqualValues(t, 12, someUint8.UnwrapOrElse(func() uint8 {
			return 13
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint8 := option.NoneUint8()
		assert.EqualValues(t, 13, emptyUint8.UnwrapOrElse(func() uint8 {
			return 13
		}))
	})
}

func TestUint8_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someUint8 := option.SomeUint8(12)
		err := someUint8.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Uint8
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, 12, unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyUint8 := option.NoneUint8()
		err := emptyUint8.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Uint8
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}
