// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option

import (
	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"
)

// Uint64 represents an optional value of type uint64.
// It can either hold a valid uint64 (IsSome == true) or be empty (IsZero == true).
type Uint64 struct {
	value  uint64
	exists bool
}

var _ commonInterface[uint64] = (*Uint64)(nil)

// SomeUint64 creates an optional Uint64 with the given uint64 value.
// The returned Uint64 will have IsSome() == true and IsZero() == false.
func SomeUint64(value uint64) Uint64 {
	return Uint64{
		value:  value,
		exists: true,
	}
}

// NoneUint64 creates an empty optional Uint64 value.
// The returned Uint64 will have IsSome() == false and IsZero() == true.
func NoneUint64() Uint64 {
	return Uint64{
		exists: false,
		value:  zero[uint64](),
	}
}

// IsSome returns true if the Uint64 contains a value.
// This indicates the value is explicitly set (not None).
func (o Uint64) IsSome() bool {
	return o.exists
}

// IsZero returns true if the Uint64 does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o Uint64) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o Uint64) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of uint64, false).
//
// Recommended usage:
//
//	if value, ok := o.Get(); ok {
//	    // use value
//	}
func (o Uint64) Get() (uint64, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o Uint64) MustGet() uint64 {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for uint64.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o Uint64) Unwrap() uint64 {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
func (o Uint64) UnwrapOr(defaultValue uint64) uint64 {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
func (o Uint64) UnwrapOrElse(defaultValue func() uint64) uint64 {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

// EncodeMsgpack encodes the Uint64 value using MessagePack format.
// - If the value is present, it is encoded as uint64.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o Uint64) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return newEncodeError("Uint64", encodeUint64(encoder, o.value))
	}

	return newEncodeError("Uint64", encoder.EncodeNil())
}

// DecodeMsgpack decodes a Uint64 value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneUint64)
//   - uint64: interpreted as a present value (SomeUint64)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on uint64: exists = true, value = decoded value
func (o *Uint64) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return newDecodeError("Uint64", err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return newDecodeError("Uint64", decoder.Skip())
	case checkNumber(code):
		o.value, err = decodeUint64(decoder)
		if err != nil {
			return newDecodeError("Uint64", err)
		}
		o.exists = true

		return err
	default:
		return newDecodeWithCodeError("Uint64", code)
	}
}
