// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"

	"github.com/tarantool/go-option"
)

func TestUint64_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint64 := option.SomeUint64(12)
		assert.True(t, someUint64.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint64 := option.NoneUint64()
		assert.False(t, emptyUint64.IsSome())
	})
}

func TestUint64_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint64 := option.SomeUint64(12)
		assert.False(t, someUint64.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint64 := option.NoneUint64()
		assert.True(t, emptyUint64.IsZero())
	})
}

func TestUint64_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint64 := option.SomeUint64(12)
		assert.False(t, someUint64.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint64 := option.NoneUint64()
		assert.True(t, emptyUint64.IsNil())
	})
}

func TestUint64_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint64 := option.SomeUint64(12)
		val, ok := someUint64.Get()
		require.True(t, ok)
		assert.EqualValues(t, 12, val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint64 := option.NoneUint64()
		_, ok := emptyUint64.Get()
		require.False(t, ok)
	})
}

func TestUint64_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint64 := option.SomeUint64(12)
		assert.EqualValues(t, 12, someUint64.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint64 := option.NoneUint64()
		assert.Panics(t, func() {
			emptyUint64.MustGet()
		})
	})
}

func TestUint64_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint64 := option.SomeUint64(12)
		assert.EqualValues(t, 12, someUint64.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint64 := option.NoneUint64()
		assert.NotPanics(t, func() {
			emptyUint64.Unwrap()
		})
	})
}

func TestUint64_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint64 := option.SomeUint64(12)
		assert.EqualValues(t, 12, someUint64.UnwrapOr(13))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint64 := option.NoneUint64()
		assert.EqualValues(t, 13, emptyUint64.UnwrapOr(13))
	})
}

func TestUint64_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint64 := option.SomeUint64(12)
		assert.EqualValues(t, 12, someUint64.UnwrapOrElse(func() uint64 {
			return 13
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint64 := option.NoneUint64()
		assert.EqualValues(t, 13, emptyUint64.UnwrapOrElse(func() uint64 {
			return 13
		}))
	})
}

func TestUint64_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someUint64 := option.SomeUint64(12)
		err := someUint64.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Uint64
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, 12, unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyUint64 := option.NoneUint64()
		err := emptyUint64.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Uint64
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}
