// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option

import (
	"bytes"
	"encoding/json"

	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"
)

// Uint32 represents an optional value of type uint32.
// It can either hold a valid uint32 (IsSome == true) or be empty (IsZero == true).
type Uint32 struct {
	value  uint32
	exists bool
}

var _ commonInterface[uint32] = (*Uint32)(nil)

// SomeUint32 creates an optional Uint32 with the given uint32 value.
// The returned Uint32 will have IsSome() == true and IsZero() == false.
func SomeUint32(value uint32) Uint32 {
	return Uint32{
		value:  value,
		exists: true,
	}
}

// NoneUint32 creates an empty optional Uint32 value.
// The returned Uint32 will have IsSome() == false and IsZero() == true.
func NoneUint32() Uint32 {
	return Uint32{
		exists: false,
		value:  zero[uint32](),
	}
}

// IsSome returns true if the Uint32 contains a value.
// This indicates the value is explicitly set (not None).
func (o Uint32) IsSome() bool {
	return o.exists
}

// IsZero returns true if the Uint32 does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o Uint32) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o Uint32) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of uint32, false).
//
// Recommended usage:
//
//	if value, ok := o.Get(); ok {
//	    // use value
//	}
func (o Uint32) Get() (uint32, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o Uint32) MustGet() uint32 {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for uint32.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o Uint32) Unwrap() uint32 {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
func (o Uint32) UnwrapOr(defaultValue uint32) uint32 {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
func (o Uint32) UnwrapOrElse(defaultValue func() uint32) uint32 {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

// EncodeMsgpack encodes the Uint32 value using MessagePack format.
// - If the value is present, it is encoded as uint32.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o Uint32) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return newEncodeError("Uint32", encodeUint32(encoder, o.value))
	}

	return newEncodeError("Uint32", encoder.EncodeNil())
}

// DecodeMsgpack decodes a Uint32 value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneUint32)
//   - uint32: interpreted as a present value (SomeUint32)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on uint32: exists = true, value = decoded value
func (o *Uint32) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return newDecodeError("Uint32", err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return newDecodeError("Uint32", decoder.Skip())
	case checkNumber(code):
		o.value, err = decodeUint32(decoder)
		if err != nil {
			return newDecodeError("Uint32", err)
		}
		o.exists = true

		return err
	default:
		return newDecodeWithCodeError("Uint32", code)
	}
}

// MarshalJSON implements the json.Marshaler interface.
//   - If the value is present, it is encoded exactly as json.Marshal encodes
//     the uint32 value itself.
//   - If the value is absent (None), it is encoded as JSON null.
//
// A struct field of type Uint32 with the "omitzero" JSON tag option is
// omitted when the value is absent, since IsZero reports absence.
// The "omitempty" option has no effect on it.
func (o Uint32) MarshalJSON() ([]byte, error) {
	if !o.exists {
		return []byte("null"), nil
	}

	return json.Marshal(&o.value)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
//   - JSON null is decoded as no value (NoneUint32).
//   - Any other JSON value is decoded as uint32 and stored as a present value.
//
// An error of decoding uint32 is returned unchanged, and the receiver
// is left intact.
func (o *Uint32) UnmarshalJSON(data []byte) error {
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		*o = NoneUint32()

		return nil
	}

	var value uint32

	err := json.Unmarshal(data, &value)
	if err != nil {
		return err
	}

	*o = SomeUint32(value)

	return nil
}

// MarshalYAML implements the Marshaler interface of gopkg.in/yaml.v3
// (and yaml.v2) without depending on it.
//   - If the value is present, it returns a pointer to it, so the value is
//     encoded exactly as the YAML encoder encodes uint32 itself.
//   - If the value is absent (None), it returns nil, which is encoded as null.
//
// A struct field of type Uint32 with the "omitempty" YAML tag option is
// omitted when the value is absent, since the encoder consults IsZero.
func (o Uint32) MarshalYAML() (any, error) {
	if !o.exists {
		return nil, nil
	}

	return &o.value, nil
}

// UnmarshalYAML implements the obsolete Unmarshaler interface of
// gopkg.in/yaml.v3 (the only one of yaml.v2) without depending on it.
//   - A null value is decoded as no value (NoneUint32).
//   - Any other value is decoded as uint32 and stored as a present value.
//
// gopkg.in/yaml.v3 never calls this method for a null node (null, ~ or an
// empty value): it leaves the receiver unchanged. Decoding null into a zero
// Uint32 therefore yields None, but decoding it into a present value
// keeps that value.
//
// An error of decoding uint32 is returned unchanged, and the receiver
// is left intact.
func (o *Uint32) UnmarshalYAML(unmarshal func(any) error) error {
	var value *uint32

	err := unmarshal(&value)
	if err != nil {
		return err
	}

	if value == nil {
		*o = NoneUint32()

		return nil
	}

	*o = SomeUint32(*value)

	return nil
}
