// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"

	"github.com/tarantool/go-option"
)

func TestUint_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint := option.SomeUint(12)
		assert.True(t, someUint.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint := option.NoneUint()
		assert.False(t, emptyUint.IsSome())
	})
}

func TestUint_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint := option.SomeUint(12)
		assert.False(t, someUint.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint := option.NoneUint()
		assert.True(t, emptyUint.IsZero())
	})
}

func TestUint_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint := option.SomeUint(12)
		assert.False(t, someUint.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint := option.NoneUint()
		assert.True(t, emptyUint.IsNil())
	})
}

func TestUint_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint := option.SomeUint(12)
		val, ok := someUint.Get()
		require.True(t, ok)
		assert.EqualValues(t, 12, val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint := option.NoneUint()
		_, ok := emptyUint.Get()
		require.False(t, ok)
	})
}

func TestUint_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint := option.SomeUint(12)
		assert.EqualValues(t, 12, someUint.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint := option.NoneUint()
		assert.Panics(t, func() {
			emptyUint.MustGet()
		})
	})
}

func TestUint_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint := option.SomeUint(12)
		assert.EqualValues(t, 12, someUint.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint := option.NoneUint()
		assert.NotPanics(t, func() {
			emptyUint.Unwrap()
		})
	})
}

func TestUint_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint := option.SomeUint(12)
		assert.EqualValues(t, 12, someUint.UnwrapOr(13))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint := option.NoneUint()
		assert.EqualValues(t, 13, emptyUint.UnwrapOr(13))
	})
}

func TestUint_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint := option.SomeUint(12)
		assert.EqualValues(t, 12, someUint.UnwrapOrElse(func() uint {
			return 13
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint := option.NoneUint()
		assert.EqualValues(t, 13, emptyUint.UnwrapOrElse(func() uint {
			return 13
		}))
	})
}

func TestUint_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someUint := option.SomeUint(12)
		err := someUint.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Uint
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, 12, unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyUint := option.NoneUint()
		err := emptyUint.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Uint
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}

func ExampleSomeUint() {
	opt := option.SomeUint(12)
	if opt.IsSome() {
		fmt.Println(opt.Unwrap())
	}
	// Output: 12
}

func ExampleNoneUint() {
	opt := option.NoneUint()
	if opt.IsZero() {
		fmt.Println("value is absent")
	}
	// Output: value is absent
}

func ExampleUint_IsSome() {
	some := option.SomeUint(12)
	none := option.NoneUint()
	fmt.Println(some.IsSome())
	fmt.Println(none.IsSome())
	// Output:
	// true
	// false
}

func ExampleUint_IsZero() {
	some := option.SomeUint(12)
	none := option.NoneUint()
	fmt.Println(some.IsZero())
	fmt.Println(none.IsZero())
	// Output:
	// false
	// true
}

func ExampleUint_IsNil() {
	some := option.SomeUint(12)
	none := option.NoneUint()
	fmt.Println(some.IsNil() == some.IsZero())
	fmt.Println(none.IsNil() == none.IsZero())
	// Output:
	// true
	// true
}

func ExampleUint_Get() {
	some := option.SomeUint(12)
	none := option.NoneUint()
	val, ok := some.Get()
	fmt.Println(val, ok)
	val, ok = none.Get()
	fmt.Println(val, ok)
	// Output:
	// 12 true
	// 0 false
}

func ExampleUint_MustGet() {
	some := option.SomeUint(12)
	fmt.Println(some.MustGet())
	// Output: 12
}

func ExampleUint_MustGet_panic() {
	none := option.NoneUint()
	eof := false
	defer func() {
		if !eof {
			fmt.Println("panic!", recover())
		}
	}()
	fmt.Println(none.MustGet())
	eof = true
	// Output: panic! optional value is not set
}

func ExampleUint_Unwrap() {
	some := option.SomeUint(12)
	none := option.NoneUint()
	fmt.Println(some.Unwrap())
	fmt.Println(none.Unwrap())
	// Output:
	// 12
	// 0
}

func ExampleUint_UnwrapOr() {
	some := option.SomeUint(12)
	none := option.NoneUint()
	fmt.Println(some.UnwrapOr(13))
	fmt.Println(none.UnwrapOr(13))
	// Output:
	// 12
	// 13
}

func ExampleUint_UnwrapOrElse() {
	some := option.SomeUint(12)
	none := option.NoneUint()
	fmt.Println(some.UnwrapOrElse(func() uint {
		return 13
	}))
	fmt.Println(none.UnwrapOrElse(func() uint {
		return 13
	}))
	// Output:
	// 12
	// 13
}
