// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option

import (
	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"
)

// Uint32 represents an optional value of type uint32.
// It can either hold a valid uint32 (IsSome == true) or be empty (IsZero == true).
type Uint32 struct {
	value  uint32
	exists bool
}

var _ commonInterface[uint32] = (*Uint32)(nil)

// SomeUint32 creates an optional Uint32 with the given uint32 value.
// The returned Uint32 will have IsSome() == true and IsZero() == false.
func SomeUint32(value uint32) Uint32 {
	return Uint32{
		value:  value,
		exists: true,
	}
}

// NoneUint32 creates an empty optional Uint32 value.
// The returned Uint32 will have IsSome() == false and IsZero() == true.
func NoneUint32() Uint32 {
	return Uint32{
		exists: false,
		value:  zero[uint32](),
	}
}

// IsSome returns true if the Uint32 contains a value.
// This indicates the value is explicitly set (not None).
func (o Uint32) IsSome() bool {
	return o.exists
}

// IsZero returns true if the Uint32 does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o Uint32) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o Uint32) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of uint32, false).
//
// Recommended usage:
//
//	if value, ok := o.Get(); ok {
//	    // use value
//	}
func (o Uint32) Get() (uint32, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o Uint32) MustGet() uint32 {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for uint32.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o Uint32) Unwrap() uint32 {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
func (o Uint32) UnwrapOr(defaultValue uint32) uint32 {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
func (o Uint32) UnwrapOrElse(defaultValue func() uint32) uint32 {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

// EncodeMsgpack encodes the Uint32 value using MessagePack format.
// - If the value is present, it is encoded as uint32.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o Uint32) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return newEncodeError("Uint32", encodeUint32(encoder, o.value))
	}

	return newEncodeError("Uint32", encoder.EncodeNil())
}

// DecodeMsgpack decodes a Uint32 value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneUint32)
//   - uint32: interpreted as a present value (SomeUint32)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on uint32: exists = true, value = decoded value
func (o *Uint32) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return newDecodeError("Uint32", err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return newDecodeError("Uint32", decoder.Skip())
	case checkNumber(code):
		o.value, err = decodeUint32(decoder)
		if err != nil {
			return newDecodeError("Uint32", err)
		}
		o.exists = true

		return err
	default:
		return newDecodeWithCodeError("Uint32", code)
	}
}
