// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option

import (
	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"
)

// Uint8 represents an optional value of type uint8.
// It can either hold a valid uint8 (IsSome == true) or be empty (IsZero == true).
type Uint8 struct {
	value  uint8
	exists bool
}

var _ commonInterface[uint8] = (*Uint8)(nil)

// SomeUint8 creates an optional Uint8 with the given uint8 value.
// The returned Uint8 will have IsSome() == true and IsZero() == false.
func SomeUint8(value uint8) Uint8 {
	return Uint8{
		value:  value,
		exists: true,
	}
}

// NoneUint8 creates an empty optional Uint8 value.
// The returned Uint8 will have IsSome() == false and IsZero() == true.
func NoneUint8() Uint8 {
	return Uint8{
		exists: false,
		value:  zero[uint8](),
	}
}

// IsSome returns true if the Uint8 contains a value.
// This indicates the value is explicitly set (not None).
func (o Uint8) IsSome() bool {
	return o.exists
}

// IsZero returns true if the Uint8 does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o Uint8) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o Uint8) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of uint8, false).
//
// Recommended usage:
//
//	if value, ok := o.Get(); ok {
//	    // use value
//	}
func (o Uint8) Get() (uint8, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o Uint8) MustGet() uint8 {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for uint8.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o Uint8) Unwrap() uint8 {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
func (o Uint8) UnwrapOr(defaultValue uint8) uint8 {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
func (o Uint8) UnwrapOrElse(defaultValue func() uint8) uint8 {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

// EncodeMsgpack encodes the Uint8 value using MessagePack format.
// - If the value is present, it is encoded as uint8.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o Uint8) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return newEncodeError("Uint8", encodeUint8(encoder, o.value))
	}

	return newEncodeError("Uint8", encoder.EncodeNil())
}

// DecodeMsgpack decodes a Uint8 value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneUint8)
//   - uint8: interpreted as a present value (SomeUint8)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on uint8: exists = true, value = decoded value
func (o *Uint8) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return newDecodeError("Uint8", err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return newDecodeError("Uint8", decoder.Skip())
	case checkNumber(code):
		o.value, err = decodeUint8(decoder)
		if err != nil {
			return newDecodeError("Uint8", err)
		}
		o.exists = true

		return err
	default:
		return newDecodeWithCodeError("Uint8", code)
	}
}
