// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"
	"gopkg.in/yaml.v3"

	"github.com/tarantool/go-option"
)

func TestUint8_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint8 := option.SomeUint8(12)
		assert.True(t, someUint8.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint8 := option.NoneUint8()
		assert.False(t, emptyUint8.IsSome())
	})
}

func TestUint8_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint8 := option.SomeUint8(12)
		assert.False(t, someUint8.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint8 := option.NoneUint8()
		assert.True(t, emptyUint8.IsZero())
	})
}

func TestUint8_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint8 := option.SomeUint8(12)
		assert.False(t, someUint8.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint8 := option.NoneUint8()
		assert.True(t, emptyUint8.IsNil())
	})
}

func TestUint8_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint8 := option.SomeUint8(12)
		val, ok := someUint8.Get()
		require.True(t, ok)
		assert.EqualValues(t, 12, val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint8 := option.NoneUint8()
		_, ok := emptyUint8.Get()
		require.False(t, ok)
	})
}

func TestUint8_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint8 := option.SomeUint8(12)
		assert.EqualValues(t, 12, someUint8.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint8 := option.NoneUint8()
		assert.Panics(t, func() {
			emptyUint8.MustGet()
		})
	})
}

func TestUint8_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint8 := option.SomeUint8(12)
		assert.EqualValues(t, 12, someUint8.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint8 := option.NoneUint8()
		assert.NotPanics(t, func() {
			emptyUint8.Unwrap()
		})
	})
}

func TestUint8_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint8 := option.SomeUint8(12)
		assert.EqualValues(t, 12, someUint8.UnwrapOr(13))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint8 := option.NoneUint8()
		assert.EqualValues(t, 13, emptyUint8.UnwrapOr(13))
	})
}

func TestUint8_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint8 := option.SomeUint8(12)
		assert.EqualValues(t, 12, someUint8.UnwrapOrElse(func() uint8 {
			return 13
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint8 := option.NoneUint8()
		assert.EqualValues(t, 13, emptyUint8.UnwrapOrElse(func() uint8 {
			return 13
		}))
	})
}

func TestUint8_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someUint8 := option.SomeUint8(12)
		err := someUint8.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Uint8
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, 12, unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyUint8 := option.NoneUint8()
		err := emptyUint8.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Uint8
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}

func TestUint8_MarshalJSON(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.SomeUint8(12))
		require.NoError(t, err)
		assert.Equal(t, `12`, string(data))
	})

	t.Run("some_as_inner_0", func(t *testing.T) {
		t.Parallel()

		expected, err := json.Marshal(uint8(12))
		require.NoError(t, err)

		data, err := json.Marshal(option.SomeUint8(12))
		require.NoError(t, err)
		assert.Equal(t, string(expected), string(data))
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.SomeUint8(0))
		require.NoError(t, err)
		assert.Equal(t, `0`, string(data))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.NoneUint8())
		require.NoError(t, err)
		assert.Equal(t, "null", string(data))
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some option.Uint8 `json:"some"`
			None option.Uint8 `json:"none"`
		}

		data, err := json.Marshal(wrapper{
			Some: option.SomeUint8(12),
			None: option.NoneUint8(),
		})
		require.NoError(t, err)
		assert.Equal(t, `{"some":12,"none":null}`, string(data))
	})

	t.Run("omitzero", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Value option.Uint8 `json:"value,omitzero"`
		}

		data, err := json.Marshal(wrapper{Value: option.NoneUint8()})
		require.NoError(t, err)
		assert.Equal(t, "{}", string(data))

		data, err = json.Marshal(wrapper{Value: option.SomeUint8(0)})
		require.NoError(t, err)
		assert.Equal(t, `{"value":0}`, string(data))
	})
}

func TestUint8_UnmarshalJSON(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var opt option.Uint8
		require.NoError(t, json.Unmarshal([]byte(`12`), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("roundtrip_0", func(t *testing.T) {
		t.Parallel()

		data, err := json.Marshal(option.SomeUint8(12))
		require.NoError(t, err)

		var opt option.Uint8
		require.NoError(t, json.Unmarshal(data, &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		var opt option.Uint8
		require.NoError(t, json.Unmarshal([]byte(`0`), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 0, opt.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeUint8(12)
		require.NoError(t, json.Unmarshal([]byte("null"), &opt))
		assert.False(t, opt.IsSome())
		assert.Zero(t, opt.Unwrap())
	})

	t.Run("none_with_spaces", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeUint8(12)
		require.NoError(t, opt.UnmarshalJSON([]byte(" null\n")))
		assert.False(t, opt.IsSome())
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some   option.Uint8 `json:"some"`
			None   option.Uint8 `json:"none"`
			Absent option.Uint8 `json:"absent"`
		}

		var out wrapper
		err := json.Unmarshal([]byte(`{"some":12,"none":null}`), &out)
		require.NoError(t, err)
		require.True(t, out.Some.IsSome())
		assert.EqualValues(t, 12, out.Some.Unwrap())
		assert.False(t, out.None.IsSome())
		assert.False(t, out.Absent.IsSome())
	})

	t.Run("invalid", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeUint8(12)
		err := opt.UnmarshalJSON([]byte("{"))

		var syntaxErr *json.SyntaxError
		require.ErrorAs(t, err, &syntaxErr)
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})
}

func TestUint8_MarshalYAML(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.SomeUint8(12))
		require.NoError(t, err)
		assert.Equal(t, "12\n", string(data))
	})

	t.Run("some_as_inner_0", func(t *testing.T) {
		t.Parallel()

		expected, err := yaml.Marshal(uint8(12))
		require.NoError(t, err)

		data, err := yaml.Marshal(option.SomeUint8(12))
		require.NoError(t, err)
		assert.Equal(t, string(expected), string(data))
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.SomeUint8(0))
		require.NoError(t, err)
		assert.Equal(t, "0\n", string(data))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.NoneUint8())
		require.NoError(t, err)
		assert.Equal(t, "null\n", string(data))
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some    option.Uint8 `yaml:"some"`
			None    option.Uint8 `yaml:"none"`
			Omitted option.Uint8 `yaml:"omitted,omitempty"`
			Zero    option.Uint8 `yaml:"zero,omitempty"`
		}

		data, err := yaml.Marshal(wrapper{
			Some:    option.SomeUint8(12),
			None:    option.NoneUint8(),
			Omitted: option.NoneUint8(),
			Zero:    option.SomeUint8(0),
		})
		require.NoError(t, err)

		var fields map[string]any
		require.NoError(t, yaml.Unmarshal(data, &fields))
		assert.Contains(t, fields, "some")
		assert.NotNil(t, fields["some"])
		assert.Contains(t, fields, "none")
		assert.Nil(t, fields["none"])
		assert.NotContains(t, fields, "omitted")
		assert.Contains(t, fields, "zero")
		assert.NotNil(t, fields["zero"])
	})
}

func TestUint8_UnmarshalYAML(t *testing.T) {
	t.Parallel()

	t.Run("roundtrip_0", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.SomeUint8(12))
		require.NoError(t, err)

		var opt option.Uint8
		require.NoError(t, yaml.Unmarshal(data, &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("some_zero", func(t *testing.T) {
		t.Parallel()

		var opt option.Uint8
		require.NoError(t, yaml.Unmarshal([]byte("0\n"), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 0, opt.Unwrap())
	})

	t.Run("none_roundtrip", func(t *testing.T) {
		t.Parallel()

		data, err := yaml.Marshal(option.NoneUint8())
		require.NoError(t, err)

		var opt option.Uint8
		require.NoError(t, yaml.Unmarshal(data, &opt))
		assert.False(t, opt.IsSome())
	})

	t.Run("null_node_keeps_present_value", func(t *testing.T) {
		t.Parallel()

		// gopkg.in/yaml.v3 does not call UnmarshalYAML for a null node.
		opt := option.SomeUint8(12)
		require.NoError(t, yaml.Unmarshal([]byte("null"), &opt))
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})

	t.Run("null_by_direct_call", func(t *testing.T) {
		t.Parallel()

		opt := option.SomeUint8(12)
		err := opt.UnmarshalYAML(func(v any) error {
			return yaml.Unmarshal([]byte("null"), v)
		})
		require.NoError(t, err)
		assert.False(t, opt.IsSome())
		assert.Zero(t, opt.Unwrap())
	})

	t.Run("struct_field", func(t *testing.T) {
		t.Parallel()

		type wrapper struct {
			Some   option.Uint8 `yaml:"some"`
			Null   option.Uint8 `yaml:"nulled"`
			Tilde  option.Uint8 `yaml:"tilde"`
			Empty  option.Uint8 `yaml:"empty"`
			Absent option.Uint8 `yaml:"absent"`
		}

		some, err := yaml.Marshal(map[string]any{"some": option.SomeUint8(12)})
		require.NoError(t, err)

		var out wrapper
		require.NoError(t, yaml.Unmarshal(append(some, []byte("nulled: null\ntilde: ~\nempty:\n")...), &out))
		require.True(t, out.Some.IsSome())
		assert.EqualValues(t, 12, out.Some.Unwrap())
		assert.False(t, out.Null.IsSome())
		assert.False(t, out.Tilde.IsSome())
		assert.False(t, out.Empty.IsSome())
		assert.False(t, out.Absent.IsSome())
	})

	t.Run("error", func(t *testing.T) {
		t.Parallel()

		errUnmarshal := errors.New("unmarshal failed")

		opt := option.SomeUint8(12)
		err := opt.UnmarshalYAML(func(any) error {
			return errUnmarshal
		})
		require.ErrorIs(t, err, errUnmarshal)
		require.True(t, opt.IsSome())
		assert.EqualValues(t, 12, opt.Unwrap())
	})
}

func ExampleUint8_MarshalJSON() {
	for _, opt := range []option.Uint8{option.SomeUint8(12), option.NoneUint8()} {
		data, err := json.Marshal(opt)
		if err != nil {
			fmt.Println("error:", err)

			return
		}

		fmt.Println(string(data))
	}
	// Output:
	// 12
	// null
}

func ExampleSomeUint8() {
	opt := option.SomeUint8(12)
	if opt.IsSome() {
		fmt.Println(opt.Unwrap())
	}
	// Output: 12
}

func ExampleNoneUint8() {
	opt := option.NoneUint8()
	if opt.IsZero() {
		fmt.Println("value is absent")
	}
	// Output: value is absent
}

func ExampleUint8_IsSome() {
	some := option.SomeUint8(12)
	none := option.NoneUint8()
	fmt.Println(some.IsSome())
	fmt.Println(none.IsSome())
	// Output:
	// true
	// false
}

func ExampleUint8_IsZero() {
	some := option.SomeUint8(12)
	none := option.NoneUint8()
	fmt.Println(some.IsZero())
	fmt.Println(none.IsZero())
	// Output:
	// false
	// true
}

func ExampleUint8_IsNil() {
	some := option.SomeUint8(12)
	none := option.NoneUint8()
	fmt.Println(some.IsNil() == some.IsZero())
	fmt.Println(none.IsNil() == none.IsZero())
	// Output:
	// true
	// true
}

func ExampleUint8_Get() {
	some := option.SomeUint8(12)
	none := option.NoneUint8()
	val, ok := some.Get()
	fmt.Println(val, ok)
	val, ok = none.Get()
	fmt.Println(val, ok)
	// Output:
	// 12 true
	// 0 false
}

func ExampleUint8_MustGet() {
	some := option.SomeUint8(12)
	fmt.Println(some.MustGet())
	// Output: 12
}

func ExampleUint8_MustGet_panic() {
	none := option.NoneUint8()
	eof := false
	defer func() {
		if !eof {
			fmt.Println("panic!", recover())
		}
	}()
	fmt.Println(none.MustGet())
	eof = true
	// Output: panic! optional value is not set
}

func ExampleUint8_Unwrap() {
	some := option.SomeUint8(12)
	none := option.NoneUint8()
	fmt.Println(some.Unwrap())
	fmt.Println(none.Unwrap())
	// Output:
	// 12
	// 0
}

func ExampleUint8_UnwrapOr() {
	some := option.SomeUint8(12)
	none := option.NoneUint8()
	fmt.Println(some.UnwrapOr(13))
	fmt.Println(none.UnwrapOr(13))
	// Output:
	// 12
	// 13
}

func ExampleUint8_UnwrapOrElse() {
	some := option.SomeUint8(12)
	none := option.NoneUint8()
	fmt.Println(some.UnwrapOrElse(func() uint8 {
		return 13
	}))
	fmt.Println(none.UnwrapOrElse(func() uint8 {
		return 13
	}))
	// Output:
	// 12
	// 13
}
