// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package option_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vmihailenco/msgpack/v5"

	"github.com/tarantool/go-option"
)

func TestUint32_IsSome(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint32 := option.SomeUint32(12)
		assert.True(t, someUint32.IsSome())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint32 := option.NoneUint32()
		assert.False(t, emptyUint32.IsSome())
	})
}

func TestUint32_IsZero(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint32 := option.SomeUint32(12)
		assert.False(t, someUint32.IsZero())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint32 := option.NoneUint32()
		assert.True(t, emptyUint32.IsZero())
	})
}

func TestUint32_IsNil(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint32 := option.SomeUint32(12)
		assert.False(t, someUint32.IsNil())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint32 := option.NoneUint32()
		assert.True(t, emptyUint32.IsNil())
	})
}

func TestUint32_Get(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint32 := option.SomeUint32(12)
		val, ok := someUint32.Get()
		require.True(t, ok)
		assert.EqualValues(t, 12, val)
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint32 := option.NoneUint32()
		_, ok := emptyUint32.Get()
		require.False(t, ok)
	})
}

func TestUint32_MustGet(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint32 := option.SomeUint32(12)
		assert.EqualValues(t, 12, someUint32.MustGet())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint32 := option.NoneUint32()
		assert.Panics(t, func() {
			emptyUint32.MustGet()
		})
	})
}

func TestUint32_Unwrap(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint32 := option.SomeUint32(12)
		assert.EqualValues(t, 12, someUint32.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint32 := option.NoneUint32()
		assert.NotPanics(t, func() {
			emptyUint32.Unwrap()
		})
	})
}

func TestUint32_UnwrapOr(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint32 := option.SomeUint32(12)
		assert.EqualValues(t, 12, someUint32.UnwrapOr(13))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint32 := option.NoneUint32()
		assert.EqualValues(t, 13, emptyUint32.UnwrapOr(13))
	})
}

func TestUint32_UnwrapOrElse(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		someUint32 := option.SomeUint32(12)
		assert.EqualValues(t, 12, someUint32.UnwrapOrElse(func() uint32 {
			return 13
		}))
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		emptyUint32 := option.NoneUint32()
		assert.EqualValues(t, 13, emptyUint32.UnwrapOrElse(func() uint32 {
			return 13
		}))
	})
}

func TestUint32_EncodeDecodeMsgpack(t *testing.T) {
	t.Parallel()

	t.Run("some", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		someUint32 := option.SomeUint32(12)
		err := someUint32.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Uint32
		err = unmarshaled.DecodeMsgpack(dec)
		require.NoError(t, err)
		assert.True(t, unmarshaled.IsSome())
		assert.EqualValues(t, 12, unmarshaled.Unwrap())
	})

	t.Run("none", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer

		enc := msgpack.NewEncoder(&buf)
		dec := msgpack.NewDecoder(&buf)

		emptyUint32 := option.NoneUint32()
		err := emptyUint32.EncodeMsgpack(enc)
		require.NoError(t, err)

		var unmarshaled option.Uint32
		err = unmarshaled.DecodeMsgpack(dec)

		require.NoError(t, err)
		assert.False(t, unmarshaled.IsSome())
	})
}
