// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package test

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"

	"github.com/tarantool/go-option"
)

// OptionalHiddenTypeAlias represents an optional value of type HiddenTypeAlias.
// It can either hold a valid HiddenTypeAlias (IsSome == true) or be empty (IsZero == true).
type OptionalHiddenTypeAlias struct {
	value  HiddenTypeAlias
	exists bool
}

var (
	_ json.Marshaler   = OptionalHiddenTypeAlias{}
	_ json.Unmarshaler = (*OptionalHiddenTypeAlias)(nil)
)

// SomeOptionalHiddenTypeAlias creates an optional OptionalHiddenTypeAlias with the given HiddenTypeAlias value.
// The returned OptionalHiddenTypeAlias will have IsSome() == true and IsZero() == false.
func SomeOptionalHiddenTypeAlias(value HiddenTypeAlias) OptionalHiddenTypeAlias {
	return OptionalHiddenTypeAlias{
		value:  value,
		exists: true,
	}
}

// NoneOptionalHiddenTypeAlias creates an empty optional OptionalHiddenTypeAlias value.
// The returned OptionalHiddenTypeAlias will have IsSome() == false and IsZero() == true.
//
// Example:
//
//	o := NoneOptionalHiddenTypeAlias()
//	if o.IsZero() {
//	    fmt.Println("value is absent")
//	}
func NoneOptionalHiddenTypeAlias() OptionalHiddenTypeAlias {
	return OptionalHiddenTypeAlias{}
}

func (o OptionalHiddenTypeAlias) newEncodeError(err error) error {
	if err == nil {
		return nil
	}
	return &option.EncodeError{
		Type:   "OptionalHiddenTypeAlias",
		Parent: err,
	}
}

func (o OptionalHiddenTypeAlias) newDecodeError(err error) error {
	if err == nil {
		return nil
	}

	return &option.DecodeError{
		Type:   "OptionalHiddenTypeAlias",
		Parent: err,
	}
}

// IsSome returns true if the OptionalHiddenTypeAlias contains a value.
// This indicates the value is explicitly set (not None).
func (o OptionalHiddenTypeAlias) IsSome() bool {
	return o.exists
}

// IsZero returns true if the OptionalHiddenTypeAlias does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o OptionalHiddenTypeAlias) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o OptionalHiddenTypeAlias) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of HiddenTypeAlias, false).
//
// Recommended usage:
//
//		if value, ok := o.Get(); ok {
//	     // use value
//		}
func (o OptionalHiddenTypeAlias) Get() (HiddenTypeAlias, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o OptionalHiddenTypeAlias) MustGet() HiddenTypeAlias {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for HiddenTypeAlias.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o OptionalHiddenTypeAlias) Unwrap() HiddenTypeAlias {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
//
// Example:
//
//	o := NoneOptionalHiddenTypeAlias()
//	v := o.UnwrapOr(someDefaultOptionalHiddenTypeAlias)
func (o OptionalHiddenTypeAlias) UnwrapOr(defaultValue HiddenTypeAlias) HiddenTypeAlias {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
//
// Example:
//
//	o := NoneOptionalHiddenTypeAlias()
//	v := o.UnwrapOrElse(func() HiddenTypeAlias { return computeDefault() })
func (o OptionalHiddenTypeAlias) UnwrapOrElse(defaultValue func() HiddenTypeAlias) HiddenTypeAlias {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

func (o OptionalHiddenTypeAlias) encodeValue(encoder *msgpack.Encoder) error {
	value, err := o.value.MarshalMsgpack()
	if err != nil {
		return err
	}

	err = encoder.EncodeExtHeader(2, len(value))
	if err != nil {
		return err
	}

	_, err = encoder.Writer().Write(value)
	if err != nil {
		return err
	}

	return nil
}

// EncodeMsgpack encodes the OptionalHiddenTypeAlias value using MessagePack format.
// - If the value is present, it is encoded as HiddenTypeAlias.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o OptionalHiddenTypeAlias) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return o.newEncodeError(o.encodeValue(encoder))
	}

	return o.newEncodeError(encoder.EncodeNil())
}

func (o *OptionalHiddenTypeAlias) decodeValue(decoder *msgpack.Decoder) error {
	tp, length, err := decoder.DecodeExtHeader()
	switch {
	case err != nil:
		return o.newDecodeError(err)
	case tp != 2:
		return o.newDecodeError(fmt.Errorf("invalid extension code: %d", tp))
	}

	a := make([]byte, length)
	if err := decoder.ReadFull(a); err != nil {
		return o.newDecodeError(err)
	}

	if err := o.value.UnmarshalMsgpack(a); err != nil {
		return o.newDecodeError(err)
	}

	o.exists = true
	return nil
}

func (o *OptionalHiddenTypeAlias) checkCode(code byte) bool {
	return msgpcode.IsExt(code)
}

// DecodeMsgpack decodes a OptionalHiddenTypeAlias value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneOptionalHiddenTypeAlias)
//   - HiddenTypeAlias: interpreted as a present value (SomeOptionalHiddenTypeAlias)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on HiddenTypeAlias: exists = true, value = decoded value
func (o *OptionalHiddenTypeAlias) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return o.newDecodeError(err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return o.newDecodeError(decoder.Skip())
	case o.checkCode(code):
		err := o.decodeValue(decoder)
		if err != nil {
			return o.newDecodeError(err)
		}
		o.exists = true

		return err
	default:
		return o.newDecodeError(fmt.Errorf("unexpected code: %d", code))
	}
}

// MarshalJSON implements the json.Marshaler interface.
//   - If the value is present, it is encoded exactly as json.Marshal encodes
//     a *HiddenTypeAlias, so MarshalJSON and MarshalText methods of HiddenTypeAlias with
//     a pointer receiver are honoured as well.
//   - If the value is absent (None), it is encoded as JSON null.
//
// A present value that itself encodes as null is encoded as null too,
// so it decodes back as an absent value.
//
// A struct field of type OptionalHiddenTypeAlias with the "omitzero" JSON tag option is
// omitted when the value is absent, since IsZero reports absence.
// The "omitempty" option has no effect on it.
func (o OptionalHiddenTypeAlias) MarshalJSON() ([]byte, error) {
	if !o.exists {
		return []byte("null"), nil
	}

	return json.Marshal(&o.value)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
//   - JSON null is decoded as no value (NoneOptionalHiddenTypeAlias).
//   - Any other JSON value is decoded as HiddenTypeAlias and stored as a present value.
//
// An error of decoding HiddenTypeAlias is returned unchanged, and the receiver
// is left intact.
func (o *OptionalHiddenTypeAlias) UnmarshalJSON(data []byte) error {
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		*o = NoneOptionalHiddenTypeAlias()

		return nil
	}

	var value HiddenTypeAlias

	err := json.Unmarshal(data, &value)
	if err != nil {
		return err
	}

	*o = SomeOptionalHiddenTypeAlias(value)

	return nil
}

// MarshalYAML implements the Marshaler interface of gopkg.in/yaml.v3
// (and yaml.v2) without depending on it.
//   - If the value is present, it returns a *HiddenTypeAlias, so the value is
//     encoded exactly as the YAML encoder encodes a *HiddenTypeAlias: MarshalYAML
//     and MarshalText methods of HiddenTypeAlias with a pointer receiver are
//     honoured as well.
//   - If the value is absent (None), it returns nil, which is encoded as null.
//
// A struct field of type OptionalHiddenTypeAlias with the "omitempty" YAML tag option is
// omitted when the value is absent, since the encoder consults IsZero.
func (o OptionalHiddenTypeAlias) MarshalYAML() (any, error) {
	if !o.exists {
		return nil, nil
	}

	return &o.value, nil
}

// UnmarshalYAML implements the obsolete Unmarshaler interface of
// gopkg.in/yaml.v3 (the only one of yaml.v2) without depending on it.
//   - A null value is decoded as no value (NoneOptionalHiddenTypeAlias).
//   - Any other value is decoded as HiddenTypeAlias and stored as a present value.
//
// gopkg.in/yaml.v3 never calls this method for a null node (null, ~ or an
// empty value): it leaves the receiver unchanged. Decoding null into a zero
// OptionalHiddenTypeAlias therefore yields None, but decoding it into a present value
// keeps that value.
//
// An error of decoding HiddenTypeAlias is returned unchanged, and the receiver
// is left intact.
func (o *OptionalHiddenTypeAlias) UnmarshalYAML(unmarshal func(any) error) error {
	var value *HiddenTypeAlias

	err := unmarshal(&value)
	if err != nil {
		return err
	}

	if value == nil {
		*o = NoneOptionalHiddenTypeAlias()

		return nil
	}

	*o = SomeOptionalHiddenTypeAlias(*value)

	return nil
}
