// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package test

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"

	"github.com/tarantool/go-option"
)

// OptionalPointerTextType represents an optional value of type PointerTextType.
// It can either hold a valid PointerTextType (IsSome == true) or be empty (IsZero == true).
type OptionalPointerTextType struct {
	value  PointerTextType
	exists bool
}

var (
	_ json.Marshaler   = OptionalPointerTextType{}
	_ json.Unmarshaler = (*OptionalPointerTextType)(nil)
)

// SomeOptionalPointerTextType creates an optional OptionalPointerTextType with the given PointerTextType value.
// The returned OptionalPointerTextType will have IsSome() == true and IsZero() == false.
func SomeOptionalPointerTextType(value PointerTextType) OptionalPointerTextType {
	return OptionalPointerTextType{
		value:  value,
		exists: true,
	}
}

// NoneOptionalPointerTextType creates an empty optional OptionalPointerTextType value.
// The returned OptionalPointerTextType will have IsSome() == false and IsZero() == true.
//
// Example:
//
//	o := NoneOptionalPointerTextType()
//	if o.IsZero() {
//	    fmt.Println("value is absent")
//	}
func NoneOptionalPointerTextType() OptionalPointerTextType {
	return OptionalPointerTextType{}
}

func (o OptionalPointerTextType) newEncodeError(err error) error {
	if err == nil {
		return nil
	}
	return &option.EncodeError{
		Type:   "OptionalPointerTextType",
		Parent: err,
	}
}

func (o OptionalPointerTextType) newDecodeError(err error) error {
	if err == nil {
		return nil
	}

	return &option.DecodeError{
		Type:   "OptionalPointerTextType",
		Parent: err,
	}
}

// IsSome returns true if the OptionalPointerTextType contains a value.
// This indicates the value is explicitly set (not None).
func (o OptionalPointerTextType) IsSome() bool {
	return o.exists
}

// IsZero returns true if the OptionalPointerTextType does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o OptionalPointerTextType) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o OptionalPointerTextType) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of PointerTextType, false).
//
// Recommended usage:
//
//		if value, ok := o.Get(); ok {
//	     // use value
//		}
func (o OptionalPointerTextType) Get() (PointerTextType, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o OptionalPointerTextType) MustGet() PointerTextType {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for PointerTextType.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o OptionalPointerTextType) Unwrap() PointerTextType {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
//
// Example:
//
//	o := NoneOptionalPointerTextType()
//	v := o.UnwrapOr(someDefaultOptionalPointerTextType)
func (o OptionalPointerTextType) UnwrapOr(defaultValue PointerTextType) PointerTextType {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
//
// Example:
//
//	o := NoneOptionalPointerTextType()
//	v := o.UnwrapOrElse(func() PointerTextType { return computeDefault() })
func (o OptionalPointerTextType) UnwrapOrElse(defaultValue func() PointerTextType) PointerTextType {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

func (o OptionalPointerTextType) encodeValue(encoder *msgpack.Encoder) error {
	value, err := o.value.MarshalMsgpack()
	if err != nil {
		return err
	}

	err = encoder.EncodeExtHeader(4, len(value))
	if err != nil {
		return err
	}

	_, err = encoder.Writer().Write(value)
	if err != nil {
		return err
	}

	return nil
}

// EncodeMsgpack encodes the OptionalPointerTextType value using MessagePack format.
// - If the value is present, it is encoded as PointerTextType.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o OptionalPointerTextType) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return o.newEncodeError(o.encodeValue(encoder))
	}

	return o.newEncodeError(encoder.EncodeNil())
}

func (o *OptionalPointerTextType) decodeValue(decoder *msgpack.Decoder) error {
	tp, length, err := decoder.DecodeExtHeader()
	switch {
	case err != nil:
		return o.newDecodeError(err)
	case tp != 4:
		return o.newDecodeError(fmt.Errorf("invalid extension code: %d", tp))
	}

	a := make([]byte, length)
	if err := decoder.ReadFull(a); err != nil {
		return o.newDecodeError(err)
	}

	if err := o.value.UnmarshalMsgpack(a); err != nil {
		return o.newDecodeError(err)
	}

	o.exists = true
	return nil
}

func (o *OptionalPointerTextType) checkCode(code byte) bool {
	return msgpcode.IsExt(code)
}

// DecodeMsgpack decodes a OptionalPointerTextType value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneOptionalPointerTextType)
//   - PointerTextType: interpreted as a present value (SomeOptionalPointerTextType)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on PointerTextType: exists = true, value = decoded value
func (o *OptionalPointerTextType) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return o.newDecodeError(err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return o.newDecodeError(decoder.Skip())
	case o.checkCode(code):
		err := o.decodeValue(decoder)
		if err != nil {
			return o.newDecodeError(err)
		}
		o.exists = true

		return err
	default:
		return o.newDecodeError(fmt.Errorf("unexpected code: %d", code))
	}
}

// MarshalJSON implements the json.Marshaler interface.
//   - If the value is present, it is encoded exactly as json.Marshal encodes
//     a *PointerTextType, so MarshalJSON and MarshalText methods of PointerTextType with
//     a pointer receiver are honoured as well.
//   - If the value is absent (None), it is encoded as JSON null.
//
// A present value that itself encodes as null is encoded as null too,
// so it decodes back as an absent value.
//
// A struct field of type OptionalPointerTextType with the "omitzero" JSON tag option is
// omitted when the value is absent, since IsZero reports absence.
// The "omitempty" option has no effect on it.
func (o OptionalPointerTextType) MarshalJSON() ([]byte, error) {
	if !o.exists {
		return []byte("null"), nil
	}

	return json.Marshal(&o.value)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
//   - JSON null is decoded as no value (NoneOptionalPointerTextType).
//   - Any other JSON value is decoded as PointerTextType and stored as a present value.
//
// An error of decoding PointerTextType is returned unchanged, and the receiver
// is left intact.
func (o *OptionalPointerTextType) UnmarshalJSON(data []byte) error {
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		*o = NoneOptionalPointerTextType()

		return nil
	}

	var value PointerTextType

	err := json.Unmarshal(data, &value)
	if err != nil {
		return err
	}

	*o = SomeOptionalPointerTextType(value)

	return nil
}

// MarshalYAML implements the Marshaler interface of gopkg.in/yaml.v3
// (and yaml.v2) without depending on it.
//   - If the value is present, it returns a *PointerTextType, so the value is
//     encoded exactly as the YAML encoder encodes a *PointerTextType: MarshalYAML
//     and MarshalText methods of PointerTextType with a pointer receiver are
//     honoured as well.
//   - If the value is absent (None), it returns nil, which is encoded as null.
//
// A struct field of type OptionalPointerTextType with the "omitempty" YAML tag option is
// omitted when the value is absent, since the encoder consults IsZero.
func (o OptionalPointerTextType) MarshalYAML() (any, error) {
	if !o.exists {
		return nil, nil
	}

	return &o.value, nil
}

// UnmarshalYAML implements the obsolete Unmarshaler interface of
// gopkg.in/yaml.v3 (the only one of yaml.v2) without depending on it.
//   - A null value is decoded as no value (NoneOptionalPointerTextType).
//   - Any other value is decoded as PointerTextType and stored as a present value.
//
// gopkg.in/yaml.v3 never calls this method for a null node (null, ~ or an
// empty value): it leaves the receiver unchanged. Decoding null into a zero
// OptionalPointerTextType therefore yields None, but decoding it into a present value
// keeps that value.
//
// An error of decoding PointerTextType is returned unchanged, and the receiver
// is left intact.
func (o *OptionalPointerTextType) UnmarshalYAML(unmarshal func(any) error) error {
	var value *PointerTextType

	err := unmarshal(&value)
	if err != nil {
		return err
	}

	if value == nil {
		*o = NoneOptionalPointerTextType()

		return nil
	}

	*o = SomeOptionalPointerTextType(*value)

	return nil
}
