// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package {{ .PackageName }}

import (
	{{ range $i, $import := .Imports }}
	"{{ $import }}"
	{{ end }}

	"fmt"

	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"

	"github.com/tarantool/go-option"
)

// {{.Name}} represents an optional value of type {{.Type}}.
// It can either hold a valid {{.Type}} (IsSome == true) or be empty (IsZero == true).
type {{.Name}} struct {
	value  {{.Type}}
	exists bool
}

// Some{{.Name}} creates an optional {{.Name}} with the given {{.Type}} value.
// The returned {{.Name}} will have IsSome() == true and IsZero() == false.
func Some{{.Name}}(value {{.Type}}) {{.Name}} {
	return {{.Name}}{
		value: value,
		exists: true,
	}
}

// None{{.Name}} creates an empty optional {{.Name}} value.
// The returned {{.Name}} will have IsSome() == false and IsZero() == true.
//
// Example:
//
//	o := None{{.Name}}()
//	if o.IsZero() {
//	    fmt.Println("value is absent")
//	}
func None{{.Name}}() {{.Name}} {
	return {{.Name}}{}
}

func (o {{.Name}}) newEncodeError(err error) error {
	if err == nil {
		return nil
	}
	return &option.EncodeError{
		Type: "{{.Name}}",
		Parent: err,
	}
}

func (o {{.Name}}) newDecodeError(err error) error {
	if err == nil {
		return nil
	}

	return &option.DecodeError{
		Type: "{{.Name}}",
		Parent: err,
	}
}

// IsSome returns true if the {{.Name}} contains a value.
// This indicates the value is explicitly set (not None).
func (o {{.Name}}) IsSome() bool {
	return o.exists
}

// IsZero returns true if the {{.Name}} does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o {{.Name}}) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o {{.Name}}) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of {{.Type}}, false).
//
// Recommended usage:
//
//	if value, ok := o.Get(); ok {
//      // use value
//	}
func (o {{.Name}}) Get() ({{.Type}}, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o {{.Name}}) MustGet() {{.Type}} {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for {{.Type}}.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o {{.Name}}) Unwrap() {{.Type}} {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
//
// Example:
//
//	o := None{{.Name}}()
//	v := o.UnwrapOr(someDefault{{.Name}})
func (o {{.Name}}) UnwrapOr(defaultValue {{.Type}}) {{.Type}} {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
//
// Example:
//
//	o := None{{.Name}}()
//	v := o.UnwrapOrElse(func() {{.Type}} { return computeDefault() })
func (o {{.Name}}) UnwrapOrElse(defaultValue func() {{.Type}}) {{.Type}} {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

func (o {{.Name}}) encodeValue(encoder *msgpack.Encoder) error {
	value, err := o.value.MarshalMsgpack()
	if err != nil {
		return err
	}

	err = encoder.EncodeExtHeader({{ .ExtCode }}, len(value))
	if err != nil {
		return err
	}

	_, err = encoder.Writer().Write(value)
	if err != nil {
		return err
	}

	return nil
}


// EncodeMsgpack encodes the {{.Name}} value using MessagePack format.
// - If the value is present, it is encoded as {{.Type}}.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o {{.Name}}) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return o.newEncodeError(o.encodeValue(encoder))
	}

	return o.newEncodeError(encoder.EncodeNil())
}

func (o *{{.Name}}) decodeValue(decoder *msgpack.Decoder) error {
	tp, length, err := decoder.DecodeExtHeader()
	switch {
	case err != nil:
		return o.newDecodeError(err)
	case tp != {{ .ExtCode }}:
		return o.newDecodeError(fmt.Errorf("invalid extension code: %d", tp))
	}

	a := make([]byte, length)
	if err := decoder.ReadFull(a); err != nil {
		return o.newDecodeError(err)
	}

	if err := o.value.UnmarshalMsgpack(a); err != nil {
		return o.newDecodeError(err)
	}

	o.exists = true
	return nil
}

func (o *{{.Name}}) checkCode(code byte) bool {
	return msgpcode.IsExt(code)
}

// DecodeMsgpack decodes a {{.Name}} value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (None{{.Name}})
//   - {{.Type}}: interpreted as a present value (Some{{.Name}})
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on {{.Type}}: exists = true, value = decoded value
func (o *{{.Name}}) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return o.newDecodeError(err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return o.newDecodeError(decoder.Skip())
	case o.checkCode(code):
		err := o.decodeValue(decoder)
		if err != nil {
			return o.newDecodeError(err)
		}
		o.exists = true

		return err
	default:
		return o.newDecodeError(fmt.Errorf("unexpected code: %d", code))
	}
}
